const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");

const html = fs.readFileSync("index.html", "utf8");
const app = fs.readFileSync("app.js", "utf8");
const styles = fs.readFileSync("styles.css", "utf8");
const server = fs.existsSync("server.js") ? fs.readFileSync("server.js", "utf8") : "";
const schema = fs.existsSync("db/schema.sql") ? fs.readFileSync("db/schema.sql", "utf8") : "";

function between(source, start, end) {
  const startIndex = source.indexOf(start);
  assert.notEqual(startIndex, -1, `Missing start marker: ${start}`);
  const endIndex = source.indexOf(end, startIndex);
  assert.notEqual(endIndex, -1, `Missing end marker: ${end}`);
  return source.slice(startIndex, endIndex);
}

test("Manager B top-level tabs are consolidated", () => {
  const managerView = between(html, '<section class="view" data-view="manager">', '<section class="view" data-view="procurement">');
  assert.match(managerView, /data-manager-tab="review">Approval</);
  assert.match(managerView, /data-manager-tab="analysis">Demand Analysis</);
  assert.match(managerView, /data-manager-tab="demand">Progress Tracking</);
  assert.match(managerView, /data-manager-tab="setup">Project Setup</);
  assert.doesNotMatch(managerView, /data-manager-tab="history"/);
  assert.match(managerView, /<h3>Approval History<\/h3>/);
});

test("Manager Demand Analysis starts with Excel Dashboard-like item x unit cost dashboard", () => {
  const analysis = between(html, 'data-manager-panel="analysis"', 'data-manager-panel="demand"');
  assert.match(analysis, /data-demand-analysis-tab="costDashboard">Cost Dashboard</);
  assert.match(analysis, /data-demand-analysis-tab="quantity">Station Matrix</);
  assert.match(analysis, /class="[^"]*demand-cost-table[^"]*"/);
  assert.match(analysis, /id="managerDemandCostLineCount"/);
  assert.match(analysis, /id="managerDemandCostUnitSummary"/);
  assert.match(analysis, /id="managerDemandCostCarryoverCompare"/);
  assert.match(analysis, /id="managerDemandCostLineCompare"/);
  assert.match(analysis, /id="managerDemandCostCarryoverLedger"/);
  assert.match(analysis, /<option value="">All stages<\/option>/);
  assert.doesNotMatch(analysis, /id="managerDemandCostSummary"/);
  const stationMatrixPanel = between(analysis, 'data-demand-analysis-panel="quantity"', '</section>');
  assert.match(stationMatrixPanel, /managerQuantityMatrixTable/);
  assert.match(stationMatrixPanel, /id="managerQuantityCarryoverLedger"/);
  assert.doesNotMatch(stationMatrixPanel, /Unit Split Dashboard/);
  assert.doesNotMatch(stationMatrixPanel, /managerQuantitySummary/);
  assert.doesNotMatch(stationMatrixPanel, /managerQuantityUnitDashboard/);
  assert.match(app, /function renderManagerDemandCostHead/);
  assert.match(app, /function renderManagerDemandCostUnitSummary/);
  assert.match(app, /function renderManagerDemandCostCarryoverCompare/);
  assert.match(app, /function renderManagerDemandCostLineCompare/);
  assert.match(app, /function renderManagerCarryoverLedger/);
  assert.match(app, /function managerDemandCostCellImpact/);
  assert.match(app, /function renderManagerDemandCostValue/);
  assert.match(app, /function managerCarryoverIsApplied/);
  assert.match(app, /function managerCarryoverStatusBucket/);
  assert.match(app, /function managerCarryoverPhaseKey/);
  assert.match(app, /function syncManagerQuantityScopeFromDemandCost/);
  assert.match(app, /procurement:carryover-updated/);
  assert.match(app, /Flow: \$\{impact\.flowLabels\.join/);
  assert.doesNotMatch(app, /<tr class="demand-cost-total-row">/);
  assert.match(app, /Department \/ Unit Cost by Selected Phase/);
  assert.match(app, /demand-cost-unit-head/);
  assert.match(app, /Original Cost/);
  assert.match(app, /Carryover Saving/);
  assert.match(app, /Effective Cost/);
  assert.match(app, /Saving %/);
  assert.match(app, /saved-badge/);
  assert.match(app, /demand-cost-cell-main/);
  assert.match(app, /demand-cost-cell-sub/);
  assert.match(app, /carryover-cell-applied/);
  assert.match(app, /carryover-cell-pending/);
  assert.match(styles, /\.line-compare-strip/);
  assert.match(styles, /\.carryover-cell-applied/);
  assert.match(styles, /\.demand-cost-cell-sub/);
  assert.match(app, /formatCompactCurrencyFromVnd/);
  assert.match(styles, /width:\s*108px/);
  ["ENG Name", "CN-ENG Name", "VN Name", "Price", "MFG", "FATP TE", "FATP IQC", "FATP PQE", "WH", "Q-LAB", "REL", "ENG1", "ENG2", "ENG3", "IT", "FAC"].forEach((label) => {
    assert.match(app, new RegExp(label.replace(".", "\\.")));
  });
  ["Highest Unit", "Highest Item", "Highest Phase"].forEach((label) => {
    assert.doesNotMatch(app, new RegExp(label));
  });
});

test("Contacts are topbar popup only, not a top-level view", () => {
  const nav = between(html, '<nav class="tabs" aria-label="Main navigation">', "</nav>");
  assert.doesNotMatch(nav, /data-view="contacts"/);
  assert.doesNotMatch(html, /<section class="view" data-view="contacts"/);
  assert.match(html, /data-action="openContactPopup"/);
  assert.match(html, /id="contactPopupModal"/);
  assert.doesNotMatch(app, /function ensureContactsTab/);
  assert.doesNotMatch(app, /function ensureContactsSection/);
  assert.doesNotMatch(app, /function renderContacts/);
  assert.doesNotMatch(app, /setView\("contacts"\)/);
});

test("OPM request workspace uses item picker and dense status tracking", () => {
  const departmentView = between(html, '<section class="view active" data-view="department">', '<section class="view" data-view="manager">');
  const opmTabs = between(departmentView, '<div class="inner-tabs" aria-label="OPM request workspace sections">', "</div>");
  assert.match(opmTabs, /Request Workspace/);
  assert.match(opmTabs, /Action Required/);
  assert.match(opmTabs, /Request Status/);
  assert.doesNotMatch(opmTabs, /My Demand Overview/);
  assert.doesNotMatch(opmTabs, /Reuse Item/);
  assert.match(departmentView, /data-action="openItemPicker"/);
  assert.match(departmentView, /id="itemPickerModal"/);
  assert.match(departmentView, /Search Catalog/);
  assert.match(departmentView, /Reuse Approved History/);
  assert.match(departmentView, /history-item-table/);
  assert.match(departmentView, /history-package-table/);
  assert.match(departmentView, /history-package-commandbar/);
  assert.match(departmentView, /class="data-table table-fixed form-table search-table" data-layout-managed="manual"/);
  assert.match(departmentView, /class="data-table table-fixed form-table history-table history-item-table" data-layout-managed="manual"/);
  const catalogTable = between(departmentView, 'class="data-table table-fixed form-table search-table" data-layout-managed="manual"', '<tbody id="naturalRows">');
  assert.match(catalogTable, /catalog-col-item/);
  assert.match(catalogTable, /catalog-col-spec/);
  assert.match(catalogTable, /catalog-col-source/);
  assert.match(catalogTable, /catalog-col-detail/);
  assert.match(catalogTable, /catalog-col-add/);
  const historyItemTable = between(departmentView, 'class="data-table table-fixed form-table history-table history-item-table" data-layout-managed="manual"', '<tbody id="historyRows">');
  assert.match(historyItemTable, /history-col-add/);
  assert.match(historyItemTable, /history-col-source-project/);
  assert.match(historyItemTable, /history-col-material/);
  assert.match(historyItemTable, /history-col-item/);
  assert.match(historyItemTable, /history-col-spec/);
  assert.match(historyItemTable, /history-col-qty-phase/);
  assert.match(historyItemTable, /history-col-detail/);
  assert.doesNotMatch(historyItemTable, /PO No\./);
  assert.match(historyItemTable, /<th>Add<\/th>\s*<th>Source Project<\/th>\s*<th>Factory Material No\.<\/th>\s*<th>Item<\/th>\s*<th>Spec<\/th>\s*<th>Qty \/ Phase<\/th>\s*<th>Detail<\/th>/);
  assert.doesNotMatch(app, />Add Item to Request<\/button>/);
  assert.match(app, />Add<\/button>/);
  assert.match(styles, /\.dense-cell-clamp/);
  assert.match(styles, /\.history-add-btn/);
  assert.match(styles, /\.item-picker-modal \.modal-footer/);
  assert.doesNotMatch(styles, /\.item-picker-section \.history-table\s*\{\s*min-width:\s*1280px;\s*\}/);
  assert.match(styles, /\.item-picker-section \.history-table:not\(\[data-layout-managed="manual"\]\)/);
  assert.doesNotMatch(styles, /\.item-picker-section \.history-table th:first-child,\s*\.item-picker-section \.history-table td:first-child/);
  const requestTable = between(departmentView, 'class="data-table table-fixed form-table request-table"', '<tbody id="requestRows">');
  assert.match(requestTable, /Spec Summary/);
  assert.match(requestTable, /Need Date/);
  assert.match(requestTable, /Qty \/ Phases/);
  assert.match(requestTable, /Timeline/);
  assert.match(requestTable, /Actions/);
  assert.doesNotMatch(requestTable, /<th>Purpose<\/th>/);
  assert.doesNotMatch(requestTable, /<th>G \/ Non-G<\/th>/);
  assert.match(app, /function openItemPicker/);
  assert.match(app, /function closeItemPicker/);
  assert.match(app, /draftTimelineCell/);
  assert.doesNotMatch(styles, /history-item-table,\s*\\n\\.history-package-table,\s*\\n\\.search-table,\s*\\n\\.request-table\s*\{[\s\S]*min-width:\s*max-content/);
  const demandEditor = between(html, 'id="demandEditorModal"', 'id="materialEntryModal"');
  assert.match(demandEditor, /Request Line/);
  assert.match(demandEditor, /Carryover From/);
  assert.match(demandEditor, /Carryover Qty/);
  assert.match(demandEditor, /Carryover Reason/);
  assert.match(app, /data-demand-editor-field="requestLine"/);
  assert.match(app, /data-demand-editor-field="carryoverFrom"/);
  assert.match(app, /data-demand-editor-field="carryoverQty"/);
  assert.match(app, /data-demand-editor-field="carryoverReason"/);
});

test("Reuse history import retargets source qty to current target phase", () => {
  const cloneReusableDemandRows = between(app, "function cloneReusableDemandRows", "function reusableReferenceFields");
  assert.match(cloneReusableDemandRows, /phase:\s*targetPhase/);
  assert.doesNotMatch(cloneReusableDemandRows, /phase:\s*stationBreakdownPhaseKey\(item\)\s*\|\|\s*targetPhase/);
  const requestFromRecord = between(app, "function requestFromRecord", "function suggestionToRecord");
  assert.match(requestFromRecord, /const draft = \{/);
  assert.match(requestFromRecord, /return syncRowPhaseQtyFromStationBreakdown\(draft\)/);
  const phaseQtySummary = between(app, "function phaseQtySummary", "function historyPackageKey");
  assert.match(phaseQtySummary, /stationBreakdownPhaseTotal\(row,\s*stage\)/);
  assert.match(app, /historyRequestOverrides\(row,\s*true,\s*\{\s*targetProject,\s*targetPhase\s*\}\)/);
});

test("Reuse by Item history rows keep source project, material, item, and spec in separate columns", () => {
  const renderHistoryRows = between(app, "function renderHistoryRows", "function omUserQuoteDecisionLabel");
  assert.match(renderHistoryRows, /history-source-project/);
  assert.doesNotMatch(renderHistoryRows, /history-po-no/);
  assert.match(renderHistoryRows, /history-material-no/);
  assert.match(renderHistoryRows, /history-item-name/);
  assert.match(renderHistoryRows, /history-spec/);
  assert.match(renderHistoryRows, /\$\{row\.project \|\| "-"\}/);
  assert.match(renderHistoryRows, /\$\{factoryMaterialNoFor\(row\) \|\| "Factory material no pending"\}/);
  assert.match(renderHistoryRows, /<td colspan="7" class="empty-cell">/);
});

test("Cost calculation uses USD canonical with VND display conversion", () => {
  assert.match(app, /function amountUsdFromVnd/);
  assert.match(app, /function amountVndFromUsd/);
  assert.match(app, /function formatMoneyFromUsd/);
  assert.match(app, /function formatMoneyFromVnd/);
  assert.match(app, /function legacyPriceToUsd/);
  assert.match(app, /function formatCompactCurrencyFromUsd/);
  assert.match(app, /function managerQuantityPriceCandidate/);
  assert.match(app, /unitPriceUsd/);
  assert.match(app, /updatedPriceUsd/);
  assert.match(app, /estimatedUnitPriceUsd/);
  assert.match(app, /estimatedAmountUsd/);
  assert.match(app, /function effectiveUnitPrice\(row\) \{\s*return legacyPriceToUsd\(row, "updatedPrice"\) \|\| legacyPriceToUsd\(row, "unitPrice"\);/);
  assert.match(app, /timestampPatch\.updatedPriceUsd = normalizedValue/);
  assert.match(app, /timestampPatch\.updatedPriceVnd = clampQty\(value\)/);
  assert.match(app, /formatCompactCurrencyFromUsd\(managerDemandCostAmount/);
});

test("Shared table and button layout standard is enforced", () => {
  assert.match(styles, /\.table-shell/);
  assert.match(styles, /\.table-fixed/);
  assert.match(styles, /\.cell-text/);
  assert.match(styles, /\.cell-spec/);
  assert.match(styles, /\.cell-number/);
  assert.match(styles, /\.cell-action/);
  assert.match(styles, /\.cell-timeline/);
  assert.match(styles, /\.form-table/);
  assert.match(styles, /\.dense-dashboard-table/);
  assert.match(styles, /\.workflow-table/);
  assert.match(styles, /\.matrix-table/);

  const departmentView = between(html, '<section class="view active" data-view="department">', '<section class="view" data-view="manager">');
  assert.match(departmentView, /table-shell form-table-shell/);
  assert.match(departmentView, /data-table table-fixed form-table request-table/);
  assert.match(departmentView, /data-table table-fixed form-table search-table/);
  assert.match(departmentView, /data-table table-fixed form-table history-table history-item-table/);
  assert.match(departmentView, /data-table table-fixed form-table history-table history-package-table/);

  const analysis = between(html, 'data-manager-panel="analysis"', 'data-manager-panel="demand"');
  assert.match(analysis, /table-wrap table-shell demand-cost-wrap/);
  assert.match(analysis, /data-table table-fixed dense-dashboard-table demand-cost-table/);

  assert.doesNotMatch(app, />Add Item to Request<\/button>/);
  assert.doesNotMatch(app, /data-edit-demand="[^"]*"[^>]*>Edit Demand<\/button>/);
  assert.match(app, /class="cell-action"/);
  assert.match(app, /class="cell-spec"/);
  assert.match(app, /class="cell-timeline"/);
  assert.match(app, /cell-spec-clamp/);
  assert.match(app, /title="Add Item to Request"[^>]*>Add<\/button>/);
});

test("v1.3 layout contract prevents recurring table and button regressions", () => {
  assert.match(styles, /v1\.3 final layout authority/);
  assert.match(styles, /body\s*\{[\s\S]*overflow-x:\s*hidden/);
  assert.match(styles, /\.item-picker-card[\s\S]*max-height:\s*calc\(100vh - 28px\)/);
  assert.match(styles, /\.item-picker-grid[\s\S]*overflow:\s*auto/);
  assert.match(styles, /\.item-picker-modal \.modal-footer[\s\S]*position:\s*sticky/);
  assert.match(styles, /\.history-item-table\[data-layout-managed="manual"\] col\.history-col-source-project[\s\S]*width:\s*130px/);
  assert.doesNotMatch(styles, /\.history-item-table\[data-layout-managed="manual"\] col\.history-col-po/);
  assert.match(styles, /\.history-item-table\[data-layout-managed="manual"\] col\.history-col-material[\s\S]*width:\s*190px/);
  assert.match(styles, /\.history-item-table\[data-layout-managed="manual"\] col\.history-col-item[\s\S]*width:\s*190px/);
  assert.match(styles, /\.history-item-table\[data-layout-managed="manual"\] td:first-child[\s\S]*position:\s*static\s*!important/);
  assert.doesNotMatch(styles, /\.history-item-table\[data-layout-managed="manual"\] th:nth-child/);
  assert.match(styles, /\.history-add-btn[\s\S]*min-width:\s*42px !important/);
  assert.match(styles, /\.cell-action[\s\S]*width:\s*76px !important/);
  assert.match(styles, /\.demand-cost-table[\s\S]*width:\s*max-content/);
  assert.match(styles, /\.demand-cost-table[\s\S]*min-width:\s*1720px/);
  assert.match(styles, /\.demand-cost-cell-btn[\s\S]*text-overflow:\s*clip/);
  assert.match(styles, /\.om-rate-utility[\s\S]*width:\s*max-content/);
  assert.match(styles, /\.om-rate-utility \.om-rate-save[\s\S]*min-width:\s*72px !important/);
  assert.doesNotMatch(app, />Add Item to Request<\/button>/);
  assert.doesNotMatch(app, />Edit Demand<\/button>/);
  assert.ok(fs.existsSync("tests/layout-smoke.js"));
  const layoutSmoke = fs.readFileSync("tests/layout-smoke.js", "utf8");
  assert.match(layoutSmoke, /assertNoPageOverflow/);
  assert.match(layoutSmoke, /assertButtonsStayInsideCells/);
  assert.match(layoutSmoke, /assertVisibleTableCellsDoNotOverlap/);
  const testScript = fs.readFileSync("test.sh", "utf8");
  assert.match(testScript, /tests\/layout-smoke\.js/);
  assert.match(testScript, /Layout smoke skipped: Playwright is not installed/);
});

test("Need Date and DRI price review layer are wired", () => {
  assert.match(html, /Employee ID \/ Account/);
  assert.match(html, /id="loginAccountInput"/);
  assert.match(html, /value="123"/);
  assert.match(html, /requester-responsibility-data\.js/);
  assert.match(app, /function findRequesterPersonaByIdentifier/);
  assert.match(app, /REQUESTER_RESPONSIBILITY_MASTER/);
  assert.match(html, /<option value="requester">Requester<\/option>/);
  assert.doesNotMatch(html, /<option value="requester">OPM \/ DRI Requester<\/option>/);
  assert.match(html, /<option value="dri">Dept DRI<\/option>/);
  assert.match(html, /<option value="projectDri">Budget Approver<\/option>/);
  assert.match(html, /data-view="priceReview"/);
  assert.match(html, /Pending Price Review/);
  assert.match(html, /Review History/);
  assert.match(html, /data-view="adminSetup"/);
  assert.match(html, /Access & Approval Setup/);
  assert.match(html, /Computer Threshold %/);
  assert.match(html, /MFG Threshold %/);
  assert.match(app, /Need Date is required/);
  assert.match(app, /data-request-need-date/);
  assert.match(app, /function renderPriceReview/);
  assert.match(app, /function applyPriceReviewDecision/);
  assert.match(app, /function priceReviewRequiresBudgetApprover/);
  assert.match(app, /Dept DRI approved\. Row moved to OM Leader Export Package queue/);
  assert.match(app, /Waiting Budget Approver/);
  assert.match(app, /function saveAdminApprovalSetup/);
  assert.match(app, /PRICE_AUTO_CLEARED/);
  assert.match(app, /PRICE_ESCALATION_REQUIRED/);
  assert.match(app, /USER_CONFIRMATION_NOT_REQUIRED/);
  assert.match(app, /Auto cleared by threshold/);
  assert.match(app, /Price escalation required/);
});

test("OM tabs and PAS quote result contract are consolidated", () => {
  const omView = between(html, '<section class="view" data-view="om">', '<section class="view" data-view="buyer">');
  assert.match(omView, /Submission Dashboard/);
  assert.match(omView, /PAS Demand No/);
  assert.match(omView, /PAS Quote Result/);
  assert.match(omView, /Export Package/);
  assert.doesNotMatch(omView, /data-om-tab="quoteExpiry"/);
  assert.doesNotMatch(omView, /data-om-panel="quoteExpiry"/);
  assert.match(omView, /Quote Expiry Monitor/);
  assert.match(omView, /class="mini approve om-rate-save"/);
  assert.match(omView, /om-rate-utility/);
  assert.match(styles, /\.om-rate-grid \.om-rate-save/);
  assert.match(styles, /min-width:\s*84px/);
  assert.match(omView, /Submitted \/ Received Date/);
  assert.match(omView, /Pending Owner/);
  assert.match(omView, /Days Pending/);
  assert.match(omView, /Quote Status/);
  assert.match(omView, /Next Action/);
  assert.doesNotMatch(omView, /<th>Budget Progress<\/th>/);
  assert.doesNotMatch(omView, /<th>PR Progress<\/th>/);
  assert.doesNotMatch(omView, /<th>PO Progress<\/th>/);
  assert.doesNotMatch(omView, /<th>Arrived Progress<\/th>/);
  assert.doesNotMatch(omView, /<th>Key Dates<\/th>/);
  assert.match(app, /function omPendingOwnerForRow/);
  assert.match(app, /function omQuoteStatusForRow/);
  assert.match(app, /function isOmExportAuthorized/);
  assert.match(app, /Only User A confirmed or price-cleared rows can be prepared/);
  assert.match(app, /return "OM Complete"/);
  assert.match(app, /Handoff complete/);
  assert.doesNotMatch(between(app, "function omNextActionForGroup", "function renderOmSubmissionExpiryMonitor"), /PR \/ PO/);
  const pasDemandTable = between(omView, 'data-om-panel="pasRequest"', 'data-om-panel="quoteConfirm"');
  assert.match(pasDemandTable, /om-pas-demand-table/);
  assert.match(pasDemandTable, /<th>CPD-IEP Owner<\/th>/);
  assert.match(pasDemandTable, /<th>Assigned To<\/th>/);
  assert.match(pasDemandTable, /<th>PAS Demand No<\/th>/);
  assert.doesNotMatch(pasDemandTable, /<th>Item Context<\/th>/);
  assert.doesNotMatch(pasDemandTable, /<th>Level 2 \/ Level 3<\/th>/);
  assert.match(app, /function pasDemandNoEntryHtml/);
  assert.match(app, /data-om-field="pasDemandNo"/);
  assert.match(app, /Enter PAS Demand No first/);
  assert.match(app, /updateOmField\(requestId, "pasDemandNo", typedDemandNo\)/);
  const quoteTable = between(omView, 'data-om-panel="quoteConfirm"', 'data-om-panel="finalExport"');
  assert.match(quoteTable, /<th>Assigned To<\/th>/);
  assert.match(quoteTable, /<th>Quote Result<\/th>/);
  assert.doesNotMatch(quoteTable, /<th>Quote Validity<\/th>/);
  assert.match(app, /Quote Valid Until/);
  assert.match(app, /currentOmTab = "submission"/);
  assert.match(app, /allowedTabs\.has\(tabName\) \? tabName : "submission"/);
  const exportPanel = between(html, 'data-om-panel="finalExport"', '<section class="view" data-view="buyer">');
  assert.match(exportPanel, /<th>Assigned To<\/th>/);
  assert.match(exportPanel, /Cost Type \/ Target/);
  assert.doesNotMatch(app, />Export Excel<\/button>/);
  assert.doesNotMatch(app, />Export Quote PDF Package<\/button>/);
  assert.match(app, /Export Package/);
  assert.match(app, /Expense → ECS \/ Capex → CFA/);
  assert.match(app, /editableMaterialNo: false/);
});

test("MySQL API Phase 1 and OM assignment contract are present", () => {
  assert.match(server, /\/api\/login/);
  assert.match(server, /function findUserByIdentifier/);
  assert.match(server, /employee_id/);
  assert.match(server, /Invalid account or password/);
  assert.match(server, /\/api\/logout/);
  assert.match(server, /\/api\/me/);
  assert.match(server, /\/api\/om\/assignees/);
  assert.match(server, /\/api\/om\/assignments/);
  assert.match(server, /api\\\/om\\\/requests\\\/\(\[\^\/\]\+\)\\\/assign/);
  assert.match(server, /mysql2\/promise/);
  assert.match(server, /process\.env\.DB_HOST/);
  assert.match(server, /process\.env\.DB_PORT/);
  assert.match(server, /process\.env\.DB_NAME/);
  assert.match(server, /function loadLocalEnv/);
  assert.match(server, /path\.join\(ROOT, "\.env"\)/);
  assert.match(server, /SESSION_TTL_HOURS/);
  assert.match(server, /mva_procurement_uat/);
  assert.match(server, /om-leader-mai/);
  assert.match(server, /om-member-giang/);
  assert.match(server, /om-member-linh/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS users/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS sessions/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS om_assignments/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS audit_events/);
  assert.match(app, /function assignOmRow/);
  assert.match(app, /function canOperateOmRow/);
  assert.match(app, /function omAssignmentCell/);
  assert.match(app, /omAssigneeId/);
  assert.match(app, /data-om-assignee-id/);
  assert.match(app, /if \(!isOmRole\(\)\) return false/);
  assert.doesNotMatch(app, /function canOperateOmRow\(row\) \{\s*if \(!isOmRole\(\)\) return true/);
  assert.match(styles, /\.om-assignment-control/);
  assert.match(styles, /\.om-pas-demand-table col\.om-pas-col-assignee/);
  assert.match(styles, /\.om-final-export-table col\.om-export-col-assignee/);
});

test("User-applied carryover stores VND price even when source row is USD canonical", () => {
  const helper = between(app, "function userCarryoverUnitPriceVnd", "function syncUserAppliedCarryoverLedger");
  assert.match(helper, /legacyPriceToUsd\(row, "updatedPrice"\)/);
  assert.match(helper, /legacyPriceToUsd\(row, "unitPrice"\)/);
  assert.match(helper, /legacyPriceToUsd\(row, "estimatedUnitPrice"\)/);
  assert.match(helper, /Math\.round\(amountVndFromUsd\(unitPriceUsd\)\)/);
  const sync = between(app, "function syncUserAppliedCarryoverLedger", "function renderDemandEditor");
  assert.match(sync, /unitPrice:\s*userCarryoverUnitPriceVnd\(row\)/);
  assert.match(sync, /unitPriceUsd:\s*amountUsdFromVnd\(userCarryoverUnitPriceVnd\(row\)\)/);
  const saving = between(app, "function managerCarryoverCostSaving", "function renderManagerCarryoverLedger");
  assert.match(saving, /row\.unitPriceUsd/);
  assert.match(saving, /amountUsdFromVnd\(clampQty\(row\.unitPrice\)\)/);
});

test("OM submission detail stays within OM ownership and export allows price-cleared rows", () => {
  const omDetail = between(app, "function openOmSubmissionDetail", "function compactList");
  assert.doesNotMatch(omDetail, /Budget Done/);
  assert.doesNotMatch(omDetail, /PR Done/);
  assert.doesNotMatch(omDetail, /PO Done/);
  assert.doesNotMatch(omDetail, /\["Arrived"/);
  assert.doesNotMatch(omDetail, /<th>PR #<\/th>/);
  assert.doesNotMatch(omDetail, /<th>PO #<\/th>/);
  assert.doesNotMatch(omDetail, /ETA \/ DTA/);
  assert.match(omDetail, /PAS Demand/);
  assert.match(omDetail, /Quote Result/);
  assert.match(omDetail, /User Confirm/);
  assert.match(omDetail, /Export Package/);
  const exportAuth = between(app, "function isOmExportAuthorized", "function isOmFinalExportPrepared");
  assert.match(exportAuth, /USER_CONFIRMATION_NOT_REQUIRED/);
  assert.match(exportAuth, /PRICE_AUTO_CLEARED/);
  assert.match(exportAuth, /PRICE_ESCALATION_APPROVED/);
});

test("Temporary budget and quote validity do not use active MutationObserver injection", () => {
  assert.doesNotMatch(app, /new MutationObserver/);
  assert.match(app, /window\.renderRequesterTempBudgetPanel = renderRequesterTempBudgetPanel/);
  assert.match(app, /Quote Valid Until/);
});

test("UI quality review documentation and skill are registered", () => {
  assert.ok(fs.existsSync("_doc/ui-quality-review.zh-TW.md"));
  assert.ok(fs.existsSync("_doc/ui-quality-review.en.md"));
  assert.ok(fs.existsSync("_doc/v0.6.md"));
  const testingZh = fs.readFileSync("_doc/testing-standard-op.zh-TW.md", "utf8");
  const testingEn = fs.readFileSync("_doc/testing-standard-op.en.md", "utf8");
  assert.match(testingZh, /procurement-ui-quality-review/);
  assert.match(testingEn, /procurement-ui-quality-review/);
});
