(function initRenderers(root, factory) {
  const api = factory(root.FihUat || {});
  if (typeof module === "object" && module.exports) module.exports = api;
  root.FihUat = Object.assign(root.FihUat || {}, api);
})(typeof globalThis !== "undefined" ? globalThis : this, function renderersFactory(core) {
  const PAGE_SIZE = 50;
  const esc = (value) => String(value == null ? "" : value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
  const roleById = (id) => core.ROLE_CATALOG.find((role) => role.id === id) || core.ROLE_CATALOG[0];
  const stageLabel = (stage) => core.STAGE_META?.[stage]?.label || stage.replace(/_/g, " ");
  const totalQty = (row) => core.totalQty ? core.totalQty(row) : Object.values(row.quantities || {}).reduce((a, b) => a + Number(b || 0), 0);
  const selectedRow = (state, rows = state.demands) => rows.find((row) => row.id === state.activeDemandId) || rows[0] || state.demands[0];
  function filteredRows(state, role) {
    let rows = core.rowsForRole(state.demands, role);
    const view = state.activeView[role];
    if (role === "requester" && view === "Request Workspace") rows = state.demands.filter((row) => row.stage === "REQUESTER_DRAFT");
    if (role === "requester" && view === "Action Required") rows = state.demands.filter((row) => row.stage === "REQUESTER_ACTION_REQUIRED");
    if (role === "requester" && view === "Request Status") rows = state.demands;
    if (role === "omMember") {
      const stage = { "My Intake": "OM_PURCHASING_INTAKE", "My Quote Result": "QUOTE_VALIDATION", "OM Handoff": "OM_HANDOFF" }[view];
      if (stage) rows = state.demands.filter((row) => row.stage === stage);
    }
    const q = String(state.search || "").toLowerCase();
    return rows.filter((row) => (!state.scope.project || row.project === state.scope.project) && (!state.scope.line || row.line === state.scope.line) && (!state.scope.mode || row.mode === state.scope.mode) && (!q || `${row.id} ${row.item} ${row.spec} ${row.pendingOwner} ${row.assignedOm}`.toLowerCase().includes(q)));
  }
  function pageRows(state, rows) { const page = Math.max(1, Math.min(state.page || 1, Math.max(1, Math.ceil(rows.length / PAGE_SIZE)))); return rows.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE); }
  function pager(state, count) { const pages = Math.max(1, Math.ceil(count / PAGE_SIZE)), page = Math.min(state.page || 1, pages); return `<div class="pager"><span>${count.toLocaleString()} rows · Page ${page}/${pages}</span><div><button type="button" data-page="${Math.max(1, page - 1)}" ${page === 1 ? "disabled" : ""}>Previous</button><button type="button" data-page="${Math.min(pages, page + 1)}" ${page === pages ? "disabled" : ""}>Next</button></div></div>`; }
  function status(row) { return `<span class="status ${row.status === "Action Required" ? "bad" : row.stage === "BUYER_HANDOFF" ? "good" : "warn"}">${esc(row.status)}</span>`; }
  function toolbar(state, rows) {
    const projects = [...new Set(state.demands.map((row) => row.project))].sort(), lines = [...new Set(state.demands.map((row) => row.line))].sort();
    const option = (value, current) => `<option value="${esc(value)}"${value === current ? " selected" : ""}>${esc(value || "All")}</option>`;
    return `<label>Project<select data-filter="project">${["", ...projects].map((v) => option(v, state.scope.project)).join("")}</select></label><label>Line<select data-filter="line">${["", ...lines].map((v) => option(v, state.scope.line)).join("")}</select></label><label>Mode<select data-filter="mode">${["", "MFG", "Non-MFG"].map((v) => option(v, state.scope.mode)).join("")}</select></label><label class="search">Search<input data-filter="search" value="${esc(state.search)}" placeholder="ID, item, spec, owner"></label><div class="toolbar-metrics"><span>Dataset <b>${state.demands.length.toLocaleString()}</b></span><span>Visible <b>${rows.length.toLocaleString()}</b></span><span>Errors <b>${rows.filter((row) => row.blockers?.length).length}</b></span></div>`;
  }
  function renderRequesterWorkspace(state, rows) {
    const view = state.activeView.requester;
    if (view === "Request Status") return renderStatusTable(state, rows, "REQUEST STATUS");
    const page = pageRows(state, rows), editable = view === "Request Workspace";
    return `<section class="panel"><div class="panel-head"><div><h2>${esc(view)}</h2><span>${esc(state.scope.project || "All projects")} · ${esc(state.scope.line || "All lines")} · ${esc(state.scope.mode || "All modes")}</span></div><div class="actions">${editable ? `<button data-action="ADD_DEMAND">Add Item</button><button data-action="SAVE_DRAFT">Save Draft</button><button data-action="SHOW_ERRORS">Show Errors</button><button class="primary" data-action="SUBMIT_SCOPE">Validate &amp; Submit Scope</button>` : ""}</div></div>${pager(state, rows.length)}<div class="table-shell"><table class="worksheet"><thead><tr><th rowspan="2">Demand / Item / Spec</th><th rowspan="2">Purpose</th><th rowspan="2">Required Delivery</th>${core.PHASES.map((phase) => `<th colspan="1">${phase}</th>`).join("")}<th rowspan="2">Total</th><th rowspan="2">State / Action</th></tr><tr>${core.PHASES.map(() => `<th>Qty</th>`).join("")}</tr></thead><tbody>${page.map((row) => `<tr class="${row.blockers?.length ? "error-row" : ""}"><td><button class="text-button" data-demand-id="${row.id}"><b>${row.id} · ${esc(row.item)}</b></button><small>${esc(row.spec)}</small></td><td>${editable ? `<select data-demand-id="${row.id}" data-demand-field="purpose"><option${row.purpose === "SMT" ? " selected" : ""}>SMT</option><option${row.purpose === "FATP" ? " selected" : ""}>FATP</option></select>` : esc(row.purpose)}</td><td>${editable ? `<input type="date" data-demand-id="${row.id}" data-demand-field="requiredDeliveryDate" value="${esc(row.requiredDeliveryDate)}">` : esc(row.requiredDeliveryDate || "Missing")}</td>${core.PHASES.map((phase) => `<td class="qty">${editable ? `<input type="number" min="0" data-demand-id="${row.id}" data-demand-field="qty.${phase}" value="${row.quantities[phase]}">` : row.quantities[phase]}</td>`).join("")}<td class="qty"><b>${totalQty(row)}</b></td><td>${status(row)}${row.blockers?.length ? `<small class="error">${esc(row.blockers[0])}</small>` : ""}<button data-demand-id="${row.id}">Detail</button></td></tr>`).join("")}</tbody></table></div>${pager(state, rows.length)}</section>${renderSelectedDetail(state, selectedRow(state, rows), view === "Action Required" ? "requester" : "")}`;
  }
  function reviewAction(row, role) {
    if (!row || !core.allowedActions(row, role).length) return "";
    return `<form class="action-form" data-workflow-form data-demand-id="${row.id}"><label>Decision reason<textarea name="reason" placeholder="Required when rejecting"></textarea></label><div class="actions"><button class="primary" type="submit" data-action="APPROVE">${role === "manager" ? "Authorize" : role === "projectDri" ? "Final Approve" : "Approve"}</button><button class="reject" type="submit" data-action="REJECT">Reject</button></div></form>`;
  }
  function renderReviewWorkspace(state, rows, role) {
    const page = pageRows(state, rows), row = selectedRow(state, rows), title = role === "dri" ? "ITEM QUANTITY REVIEW" : role === "manager" ? "COST REVIEW" : "BUDGET EXCEPTION REVIEW";
    return `<section class="panel"><div class="panel-head"><div><h2>${title}</h2><span>Dashboard-first queue and quantity evidence</span></div></div>${pager(state, rows.length)}<div class="table-shell"><table><thead><tr><th>Review Status</th><th>Demand</th><th>Project / Line</th><th>Item / Spec</th><th>Qty</th><th>${role === "projectDri" ? "USD Delta" : "Estimated Cost"}</th><th>Pending Owner</th><th>Risk</th><th>Action</th></tr></thead><tbody>${page.map((item) => `<tr class="${item.id === row?.id ? "selected-row" : ""}"><td>${status(item)}</td><td>${item.id}</td><td>${item.project}<small>${item.line} · ${item.mode}</small></td><td><b>${esc(item.item)}</b><small>${esc(item.spec)}</small></td><td class="qty">${totalQty(item)}</td><td class="qty">${role === "projectDri" ? `$${(0.41 + Number(item.id.slice(-2)) / 100).toFixed(2)}` : `${Number(item.estimatedUnitPrice).toLocaleString()} VND`}</td><td>${esc(item.pendingOwner)}</td><td>${item.blockers?.length ? `<span class="error">${esc(item.blockers[0])}</span>` : "Normal"}</td><td><button data-demand-id="${item.id}">Review</button></td></tr>`).join("")}</tbody></table></div></section><div class="detail-grid"><section class="panel compact"><div class="panel-head"><h2>Demand Cost Dashboard / Station Matrix</h2></div>${quantityEvidence(row)}</section><section class="panel compact"><div class="panel-head"><h2>Decision</h2></div>${reviewAction(row, role) || `<div class="empty">Select an actionable row.</div>`}</section></div>`;
  }
  function quantityEvidence(row) { if (!row) return `<div class="empty">No row selected.</div>`; return `<div class="detail-summary"><div><span>Demand</span><b>${row.id}</b></div><div><span>Project</span><b>${row.project}</b></div><div><span>Purpose</span><b>${row.purpose}</b></div><div><span>Required Delivery</span><b>${row.requiredDeliveryDate || "Missing"}</b></div>${core.PHASES.map((phase) => `<div><span>${phase}</span><b>${row.quantities[phase]}</b></div>`).join("")}</div>`; }
  function renderOmLeaderWorkspace(state, rows) {
    const view = state.activeView.omLeader;
    if (view === "Project Stage Calendar") return `<section class="panel"><div class="panel-head"><h2>PROJECT STAGE CALENDAR</h2></div><form class="form-grid" data-stage-calendar><label>Project<select name="project">${[...new Set(state.demands.map((row) => row.project))].map((p) => `<option>${p}</option>`).join("")}</select></label><label>Phase<select name="phase">${core.PHASES.map((p) => `<option>${p}</option>`).join("")}</select></label><label>Line Open Date<input type="date" name="date" required></label><button class="primary" type="submit" data-action="SAVE_STAGE_DATE">Save Stage Date</button></form><div class="table-shell"><table><thead><tr><th>Project / Phase</th><th>Line Open Date</th><th>Source</th></tr></thead><tbody>${Object.entries(state.stageCalendar).map(([key, date]) => `<tr><td>${esc(key.replace("|", " · "))}</td><td>${esc(date)}</td><td>OM Leader DEMO input</td></tr>`).join("")}</tbody></table></div></section>`;
    const page = pageRows(state, rows), row = selectedRow(state, rows);
    return `<section class="panel"><div class="panel-head"><div><h2>${esc(view)}</h2><span>Assignment, workload, aging and risk</span></div></div>${pager(state, rows.length)}<div class="table-shell"><table><thead><tr><th>Demand</th><th>Project</th><th>Item / Spec</th><th>Stage</th><th>Assigned OM</th><th>Risk</th><th>Action</th></tr></thead><tbody>${page.map((item) => `<tr><td>${item.id}</td><td>${item.project}<small>${item.line}</small></td><td><b>${esc(item.item)}</b><small>${esc(item.spec)}</small></td><td>${stageLabel(item.stage)}</td><td>${esc(item.assignedOm || "Unassigned")}</td><td>${item.blockers?.length ? `<span class="error">${esc(item.blockers[0])}</span>` : "Normal"}</td><td><button data-demand-id="${item.id}">Open</button></td></tr>`).join("")}</tbody></table></div></section><section class="panel compact"><div class="panel-head"><h2>Assignment Control</h2></div>${row?.stage === "OM_LEADER_ASSIGNMENT" ? `<form class="action-form" data-workflow-form data-demand-id="${row.id}"><label>Assigned OM<select name="assignedOm"><option>Giang</option><option>Linh</option></select></label><button class="primary" type="submit" data-action="ASSIGN">Assign</button></form>` : `<div class="empty">Select an unassigned row to assign; other rows are progress-only.</div>`}</section>`;
  }
  function omForm(row) {
    if (!row) return `<div class="empty">No assigned row in this view.</div>`;
    const base = `<div class="stepper"><span class="${row.stage === "OM_PURCHASING_INTAKE" ? "current" : "done"}">1 PAS Intake</span><span class="${row.stage === "QUOTE_VALIDATION" ? "current" : row.stage === "OM_HANDOFF" ? "done" : ""}">2 Quote Result</span><span class="${row.stage === "OM_HANDOFF" ? "current" : ""}">3 OM Handoff</span></div>`;
    if (row.stage === "OM_PURCHASING_INTAKE") return `${base}<form class="form-grid" data-workflow-form data-demand-id="${row.id}"><label>PAS Demand No<input name="pasDemandNo" value="${esc(row.pasDemandNo)}" ${row.pasRequired ? "required" : ""}></label><label>PAS Material No<input name="pasMaterialNo" value="${esc(row.pasMaterialNo)}"></label><button class="primary" type="submit" data-action="SAVE_INTAKE">Save PAS &amp; Continue</button></form>`;
    if (row.stage === "QUOTE_VALIDATION") return `${base}<form class="form-grid" data-workflow-form data-demand-id="${row.id}"><label>Vendor Name<input name="vendorName" required></label><label>Vendor Number<input name="vendorNumber" required></label><label>Currency<select name="currency"><option>VND</option><option>USD</option></select></label><label>Unit Price<input name="unitPrice" type="number" min="1" required></label><label>Quote Date<input name="quoteDate" type="date" required></label><label>Quote Valid Until<input name="quoteValidUntil" type="date" required></label><label>Quote Screenshot Reference<input name="quoteReference" placeholder="quote-screen.png" required></label><button class="primary" type="submit" data-action="VALIDATE_QUOTE">Validate Quote</button></form>`;
    return `${base}<form class="form-grid" data-workflow-form data-demand-id="${row.id}"><label>Budget Status<select name="budgetStatus"><option>Approved</option><option>Pending</option></select></label><label>Budget #<input name="budgetNo"></label><label>PR Status<select name="prStatus"><option>Created</option><option>Pending</option></select></label><label>PR #<input name="prNo"></label><label>PO Status<select name="poStatus"><option>Released</option><option>Pending</option></select></label><label>PO #<input name="poNo"></label><label>ETA (PLAN)<input type="date" name="etaPlan" required></label><label>DTA (Actual)<input type="date" name="dtaActual"></label><label>#PUR request NO<input name="purRequestNo" required></label><label>Total lead time<input type="number" name="totalLeadTime" min="1" required></label><button class="primary" type="submit" data-action="HANDOFF">Send to Buyer Handoff</button></form>`;
  }
  function renderOmWorkspace(state, rows) {
    if (state.activeView.omMember === "Quotation DB") return `<section class="panel"><div class="panel-head"><h2>QUOTATION DB · DEMO RETENTION VIEW</h2></div>${renderStatusTable(state, state.demands.filter((row) => row.vendorName), "Reusable quote candidates", false)}</section>`;
    const page = pageRows(state, rows), row = selectedRow(state, rows);
    return `<section class="panel"><div class="panel-head"><div><h2>${esc(state.activeView.omMember).toUpperCase()}</h2><span>Assigned work queue</span></div></div>${pager(state, rows.length)}<div class="table-shell"><table><thead><tr><th>Stage</th><th>PAS Demand</th><th>Demand / Project</th><th>Item / Spec</th><th>Qty</th><th>Need Date</th><th>Assigned OM</th><th>Blocker</th><th>Action</th></tr></thead><tbody>${page.map((item) => `<tr class="${item.id === row?.id ? "selected-row" : ""}"><td>${stageLabel(item.stage)}</td><td>${esc(item.pasDemandNo || "—")}</td><td>${item.id}<small>${item.project} · ${item.line}</small></td><td><b>${esc(item.item)}</b><small>${esc(item.spec)}</small></td><td class="qty">${totalQty(item)}</td><td>${esc(item.requiredDeliveryDate || "Missing")}</td><td>${esc(item.assignedOm || "Unassigned")}</td><td>${item.blockers?.length ? `<span class="error">${esc(item.blockers[0])}</span>` : "—"}</td><td><button data-demand-id="${item.id}">Open Workbench</button></td></tr>`).join("")}</tbody></table></div></section><div class="detail-grid"><section class="panel compact"><div class="panel-head"><h2>Selected Row</h2></div>${quantityEvidence(row)}<p><b>Purpose:</b> ${esc(row?.purpose || "—")} <span class="muted">(Requester-owned, read-only)</span></p></section><section class="panel compact"><div class="panel-head"><h2>PAS → Quote → Handoff Workbench</h2></div>${omForm(row)}</section></div>`;
  }
  function renderBuyerWorkspace(state, rows) { return renderStatusTable(state, rows, "BUYER HANDOFF · READ ONLY"); }
  function renderAdminWorkspace(state) { return `<section class="panel"><div class="panel-head"><div><h2>${esc(state.activeView.admin).toUpperCase()}</h2><span>Governance only · no business approval</span></div></div><form class="form-grid" data-admin-setting><label>Price threshold (USD)<input name="priceThresholdUsd" type="number" step="0.01" value="${esc(state.settings.priceThresholdUsd)}"></label><label>Approval Chain<input name="approvalChain" value="${esc(state.settings.approvalChain)}"></label><label>OM Assignment Rule<input name="omRule" value="${esc(state.settings.omRule)}"></label><button class="primary" type="submit" data-action="SAVE_SETTING">Save Configuration</button></form><div class="table-shell"><table><thead><tr><th>Setting</th><th>Current Value</th><th>Owner</th><th>Business Approval</th></tr></thead><tbody>${Object.entries(state.settings).map(([key, value]) => `<tr><td>${esc(key)}</td><td>${esc(value)}</td><td>Admin</td><td>Not allowed</td></tr>`).join("")}</tbody></table></div></section>`; }
  function renderStatusTable(state, rows, title, wrap = true) { const page = pageRows(state, rows), content = `<div class="panel-head"><h2>${esc(title)}</h2></div>${pager(state, rows.length)}<div class="table-shell"><table><thead><tr><th>Demand</th><th>Project / Line</th><th>Item / Spec</th><th>Qty</th><th>Current Stage</th><th>Pending Owner</th><th>Next Action</th><th>Status</th><th>Detail</th></tr></thead><tbody>${page.map((row) => `<tr><td>${row.id}</td><td>${row.project}<small>${row.line} · ${row.mode}</small></td><td><b>${esc(row.item)}</b><small>${esc(row.spec)}</small></td><td class="qty">${totalQty(row)}</td><td>${stageLabel(row.stage)}</td><td>${esc(row.pendingOwner)}</td><td>${esc(row.nextAction)}</td><td>${status(row)}</td><td><button data-demand-id="${row.id}">Detail</button></td></tr>`).join("")}</tbody></table></div>`; return wrap ? `<section class="panel">${content}</section>` : content; }
  function renderSelectedDetail(state, row, role) { if (!row) return ""; const action = role === "requester" && row.stage === "REQUESTER_ACTION_REQUIRED" ? `<form class="action-form" data-workflow-form data-demand-id="${row.id}"><label>Revision Note<textarea name="revisionNote" required></textarea></label><button class="primary" type="submit" data-action="RESUBMIT">Resubmit</button></form>` : ""; return `<section class="panel compact"><div class="panel-head"><h2>Selected Demand ${row.id}</h2></div>${quantityEvidence(row)}${action}<div class="timeline"><b>Recent timeline</b>${[...row.timeline].reverse().slice(0, 5).map((event) => `<p>${esc(event.at.slice(0, 19).replace("T", " "))} · ${esc(event.actorRole)} · ${esc(event.action)} · ${esc(event.reason || "—")}</p>`).join("")}</div></section>`; }
  function renderApp(state, session = null) {
    const documentRef = globalThis.document;
    const loginScreen = documentRef.getElementById("loginScreen");
    const workspaceScreen = documentRef.getElementById("workspaceScreen");
    if (!session) {
      loginScreen.hidden = false;
      workspaceScreen.hidden = true;
      return;
    }
    loginScreen.hidden = true;
    workspaceScreen.hidden = false;
    const role = roleById(session.role), rows = filteredRows(state, role.id);
    documentRef.getElementById("workflowSidebar").innerHTML = `<div class="workflow-group-label">${esc(role.label)}</div>${role.nav.map((view) => `<button class="workflow-item${state.activeView[role.id] === view ? " active" : ""}" data-view="${esc(view)}">${esc(view)}</button>`).join("")}`;
    documentRef.getElementById("workspaceToolbar").innerHTML = toolbar(state, rows);
    let html = "";
    if (role.id === "requester") html = renderRequesterWorkspace(state, rows); else if (["dri", "manager", "projectDri"].includes(role.id)) html = renderReviewWorkspace(state, rows, role.id); else if (role.id === "omLeader") html = renderOmLeaderWorkspace(state, rows); else if (role.id === "omMember") html = renderOmWorkspace(state, rows); else if (role.id === "buyer") html = renderBuyerWorkspace(state, rows); else html = renderAdminWorkspace(state);
    documentRef.getElementById("workspaceContent").innerHTML = html;
    documentRef.getElementById("datasetCount").textContent = state.demands.length.toLocaleString();
    documentRef.getElementById("pageTitle").textContent = role.label;
    documentRef.getElementById("userBlock").innerHTML = `<b>Name: ${esc(session.name)}</b><span>Dept: ${esc(session.dept)}</span><br><span>Function: ${esc(session.functionName)}</span><br><span>Account: ${esc(session.account)}</span>`;
    documentRef.getElementById("noticeRegion").innerHTML = (state.notices || []).map((n) => `<div class="notice ${esc(n.type)}">${esc(n.message)}</div>`).join("");
  }
  return { PAGE_SIZE, filteredRows, renderRequesterWorkspace, renderReviewWorkspace, renderOmLeaderWorkspace, renderOmWorkspace, renderBuyerWorkspace, renderAdminWorkspace, renderApp };
});
