const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");

const html = fs.readFileSync("index.html", "utf8");
const app = fs.readFileSync("app.js", "utf8");
const roleGuards = fs.readFileSync("app-modules/role-guards.js", "utf8");
const workflowStatusModule = fs.readFileSync("app-modules/workflow-status.js", "utf8");
const approvalReviewSurfaceModule = fs.readFileSync("app-modules/approval-review-surface.js", "utf8");
const sapPoRawContractModule = fs.readFileSync("app-modules/sap-po-raw-contract.js", "utf8");
const styles = fs.readFileSync("styles.css", "utf8");
const server = fs.existsSync("server.js") ? fs.readFileSync("server.js", "utf8") : "";
const schema = fs.existsSync("db/schema.sql") ? fs.readFileSync("db/schema.sql", "utf8") : "";
const workflowMigration = fs.existsSync("db/migrations/001_target_workflow_tables.sql")
  ? fs.readFileSync("db/migrations/001_target_workflow_tables.sql", "utf8")
  : "";
const sapPoRawMigration = fs.existsSync("db/migrations/002_sap_po_raw_mirror.sql")
  ? fs.readFileSync("db/migrations/002_sap_po_raw_mirror.sql", "utf8")
  : "";
const sapPoRawScopeMigration = fs.existsSync("db/migrations/003_sap_po_raw_scope.sql")
  ? fs.readFileSync("db/migrations/003_sap_po_raw_scope.sql", "utf8")
  : "";
const projectDecisions = fs.existsSync("PROJECT_DECISIONS.md") ? fs.readFileSync("PROJECT_DECISIONS.md", "utf8") : "";
const dataDictionary = fs.existsSync("docs-current/data-dictionary-en.md") ? fs.readFileSync("docs-current/data-dictionary-en.md", "utf8") : "";
const namingRulesZh = fs.existsSync("docs-current/it-handoff/zh-TW/00-naming-rules.md")
  ? fs.readFileSync("docs-current/it-handoff/zh-TW/00-naming-rules.md", "utf8")
  : "";
const dockerfile = fs.existsSync("Dockerfile") ? fs.readFileSync("Dockerfile", "utf8") : "";
const macMiniCompose = fs.existsSync("../deploy/mac-mini/docker-compose.yml")
  ? fs.readFileSync("../deploy/mac-mini/docker-compose.yml", "utf8")
  : "";
const sapPoRawCommitScript = fs.existsSync("scripts/commit-sap-po-raw-import.js")
  ? fs.readFileSync("scripts/commit-sap-po-raw-import.js", "utf8")
  : "";

function between(source, start, end) {
  const startIndex = source.indexOf(start);
  assert.notEqual(startIndex, -1, `Missing start marker: ${start}`);
  const endIndex = source.indexOf(end, startIndex);
  assert.notEqual(endIndex, -1, `Missing end marker: ${end}`);
  return source.slice(startIndex, endIndex);
}

test("Docker runtime does not expose private source and workflow schema is migration-owned", () => {
  assert.match(server, /PUBLIC_ROOT_FILES/);
  assert.match(server, /publicAssetPath/);
  assert.match(server, /SELECT 1 AS ok/);
  assert.doesNotMatch(schema, /CREATE TABLE IF NOT EXISTS item_master_requests/);
  assert.match(workflowMigration, /CREATE TABLE IF NOT EXISTS item_master_requests/);
  assert.match(workflowMigration, /CONSTRAINT fk_item_master_requests_request_item/);
});

test("Mac mini Docker runtime supports SAP PO Raw Excel import", () => {
  assert.match(dockerfile, /python3-openpyxl/);
  assert.match(dockerfile, /\/var\/lib\/mva-procurement\/imports/);
  assert.match(macMiniCompose, /SAP_PO_RAW_WORKBOOK_PATH/);
  assert.match(macMiniCompose, /\.\/imports:\/var\/lib\/mva-procurement\/imports:ro/);
  assert.match(sapPoRawCommitScript, /--require-clean-preview/);
  assert.match(sapPoRawCommitScript, /commitSapPoRawImport/);
  assert.match(sapPoRawCommitScript, /postCommitChecks/);
});

test("Cost Manager top-level tabs are consolidated", () => {
  const managerView = between(html, '<section class="view" data-view="manager" data-approval-review-role="manager">', '<section class="view" data-view="procurement">');
  assert.match(managerView, /data-approval-review-role="manager"/);
  const managerTabs = between(managerView, '<div class="inner-tabs manager-tabs"', "</div>");
  assert.match(managerTabs, /data-manager-tab="review">Cost Review</);
  assert.match(managerTabs, /data-manager-tab="history">Review History</);
  assert.doesNotMatch(managerTabs, /Submission Monitor|Authorized Analysis|Demand Analysis|Progress Tracking|Project Setup/);
  assert.doesNotMatch(managerTabs, /data-manager-tab="authorized"|data-manager-tab="analysis"|data-manager-tab="demand"|data-manager-tab="setup"/);
  assert.doesNotMatch(managerView, /<h3>Cost Review Workbench<\/h3>/);
  assert.match(managerView, /<h3>Quantity Review<\/h3>/);
  assert.match(managerView, /id="managerApprovalQuantityTabs"/);
  assert.match(managerView, /data-manager-panel="analysis"/);
  assert.match(managerView, /id="managerDemandCostTable"/);
  assert.match(managerView, /id="managerQuantityMatrixTable"/);
  assert.match(managerView, /id="managerDemandCostLineFilter"/);
  assert.match(managerView, /id="managerQuantityLineFilter"/);
  assert.match(managerView, /<h3>Cost Review History<\/h3>/);
  assert.match(managerView, /Cost Manager Decision/);
  assert.match(app, /data-cost-manager-authorization/);
  assert.match(app, /data-cost-manager-action="reject"/);
  assert.match(managerView, /id="managerQueue" class="pending-work-host"/);
  assert.match(managerView, /id="managerAuthorizedAnalysis" class="price-review-inline-analysis" hidden/);
  assert.match(app, /function renderApprovalQuantityRowPicker/);
  assert.match(app, /approvalQuantityReviewModule\(\)\.renderRowPicker/);
  assert.match(app, /function renderManagerReviewEvidencePanel/);
  assert.doesNotMatch(app, /data-approval-shell="manager"/);
  assert.match(app, /managerTabs:\s*\["review",\s*"history"\]/);
  assert.doesNotMatch(managerView, /data-manager-panel="demand"|managerDemandOverviewTable|managerStageRows|managerProgressYearFilter/);
});

test("Dept DRI, Cost Manager, and Budget Approver use one approval review surface contract", () => {
  assert.match(html, /app-modules\/approval-review-surface\.js/);
  assert.match(html, /data-view="manager" data-approval-review-role="manager"/);
  assert.match(html, /data-view="priceReview" data-approval-review-role="dri"/);
  assert.match(approvalReviewSurfaceModule, /ApprovalReviewRoleConfig|roleKey/);
  assert.match(approvalReviewSurfaceModule, /dri:\s*\{/);
  assert.match(approvalReviewSurfaceModule, /manager:\s*\{/);
  assert.match(approvalReviewSurfaceModule, /projectDri:\s*\{/);
  assert.match(approvalReviewSurfaceModule, /entryLabel:\s*"Dept Review"/);
  assert.match(approvalReviewSurfaceModule, /entryLabel:\s*"Cost Review"/);
  assert.match(approvalReviewSurfaceModule, /entryLabel:\s*"Budget Review"/);
  assert.match(approvalReviewSurfaceModule, /const REVIEW_HISTORY_TABS = \["pending", "history"\]/);
  assert.match(approvalReviewSurfaceModule, /pending:\s*"Dept Review"/);
  assert.match(approvalReviewSurfaceModule, /pending:\s*"Budget Review"/);
  assert.match(approvalReviewSurfaceModule, /defaultQueue:\s*"submission"/);
  assert.match(approvalReviewSurfaceModule, /defaultQueue:\s*"authorization"/);
  assert.match(approvalReviewSurfaceModule, /defaultQueue:\s*"budget"/);
  assert.match(approvalReviewSurfaceModule, /decisionActions/);
  assert.match(approvalReviewSurfaceModule, /Final Approve/);
  assert.match(approvalReviewSurfaceModule, /approvalReviewState/);
  assert.match(app, /function approvalReviewSurfaceModule/);
  assert.match(app, /function approvalReviewConfigForRole/);
  assert.match(app, /function approvalReviewStateForRole/);
  assert.match(app, /workspaceConfigForRole[\s\S]*approvalReviewSurfaceModule\(\)\?\.workspaceConfig/);
  assert.match(app, /availablePriceReviewQueues[\s\S]*approvalReviewSurfaceModule/);
  assert.match(app, /updateApprovalReviewState\("manager"/);
  assert.match(app, /updateApprovalReviewState\(currentRole/);
  assert.match(app, /setProjectContextSelectedProject[\s\S]*updateApprovalReviewState/);
  assert.match(app, /syncSelectedManagerRequest[\s\S]*selectedRowId/);
  assert.match(app, /syncSelectedPriceReviewRequest[\s\S]*selectedRowId/);
  assert.match(fs.readFileSync("app-modules/role-queue-config.js", "utf8"), /approvalReviewSurface/);
});

test("Cost Manager review embeds protected Demand Analysis baseline instead of duplicate Project Context evidence", () => {
  const managerView = between(html, '<section class="view" data-view="manager" data-approval-review-role="manager">', '<section class="view" data-view="procurement">');
  const reviewPanel = between(managerView, 'data-manager-panel="review"', 'data-manager-panel="history"');
  const analysisPanel = between(managerView, 'data-manager-panel="analysis"', 'data-manager-panel="setup"');
  assert.doesNotMatch(reviewPanel, /Cost Review Workbench/);
  assert.match(app, /renderViewTabs/);
  assert.match(reviewPanel, /id="managerApprovalQuantityTabs"/);
  assert.match(reviewPanel, /Quantity Review/);
  assert.match(analysisPanel, /Demand Cost Dashboard/);
  assert.match(analysisPanel, /Station Matrix/);
  assert.match(analysisPanel, /id="managerDemandCostTable"/);
  assert.match(analysisPanel, /id="managerQuantityMatrixTable"/);
  assert.match(analysisPanel, /id="managerDemandCostLineFilter"/);
  assert.match(analysisPanel, /id="managerQuantityLineFilter"/);
  assert.doesNotMatch(analysisPanel, /managerDemandCostCarryoverLedger|managerQuantityCarryoverLedger|Confirmed Carryover Saving|Line Carryover Impact|Carryover Ledger/);
  assert.match(app, /function renderManagerDemandAnalysisEvidence/);
  assert.match(app, /renderManagerDemandCostDashboard\(\{\s*showCarryoverEvidence:\s*false\s*\}\)/);
  assert.match(app, /renderManagerQuantityMatrix\(\{\s*showCarryoverEvidence:\s*false\s*\}\)/);
  assert.match(app, /function reviewStatusForRole/);
  assert.match(app, /function reviewStatusCellHtml/);
  assert.match(app, /function roleReviewRows/);
  assert.match(app, /<th>Review Status<\/th>/);
  assert.match(app, /"Review Status", "Actions", "Request ID"/);
  assert.match(fs.readFileSync("app-modules/approval-quantity-review.js", "utf8"), /<th>Review Status<\/th>/);
  assert.doesNotMatch(app, /Project Status/);
  assert.match(styles, /\.demand-cost-col-review-status/);
  assert.match(styles, /\.review-status-cell/);
  assert.match(app, /function managerCarryoverEvidenceHtml/);
  assert.match(app, /Current Owner[\s\S]*Current Stage[\s\S]*Aging[\s\S]*Next Action/);
  assert.doesNotMatch(app, /renderManagerReviewEvidencePanel\(selectedRow,\s*rows\)/);
  assert.match(app, /demand-cost-col-request/);
  assert.match(app, /<th>Request ID<\/th>/);
  assert.match(app, /managerQuantityGroupKey\(row\)[\s\S]*row\.id/);
  assert.match(app, /data-manager-select-row/);
  assert.match(app, /data-manager-authorized-select-row/);
  assert.match(app, /requestLine:\s*document\.getElementById\("managerDemandCostLineFilter"\)/);
  assert.match(app, /managerQuantityRequestLine/);
  assert.match(app, /managerDemandCostRows\(\)[\s\S]*filters\.requestLine/);
  assert.match(app, /managerQuantityFilteredEntries\(\)[\s\S]*filters\.requestLine/);
  assert.match(app, /function approvedRowsForRole/);
  assert.match(app, /You approved/);
  assert.match(app, /You authorized/);
  assert.match(app, /Final approved/);
  assert.match(app, /Pending Cost Manager/);
  assert.match(app, /Pending Budget Approver/);
  assert.match(app, /role === "manager"/);
  assert.match(app, /costManagerAuthorizedAt/);
  assert.match(app, /costManagerAuthorizationStatus === COST_MANAGER_AUTH_APPROVED/);
});

test("Approval quantity review module provides row picker plus three-layer matrix views", () => {
  const moduleSource = fs.readFileSync("app-modules/approval-quantity-review.js", "utf8");
  assert.match(html, /app-modules\/approval-quantity-review\.js/);
  assert.match(moduleSource, /renderViewTabs/);
  assert.match(moduleSource, /renderRowPicker/);
  assert.match(moduleSource, /approval-quantity-chip-action/);
  assert.doesNotMatch(moduleSource, /renderProjectItemMatrixOverview/);
  assert.match(moduleSource, /renderDashboardParts/);
  assert.match(moduleSource, /<th>Review Status<\/th>/);
  assert.match(moduleSource, /reviewStatusHtml/);
  assert.match(moduleSource, /reviewStatusFallback/);
  assert.doesNotMatch(moduleSource, /Project Status/);
  assert.match(moduleSource, /renderItemUnitMatrixParts/);
  assert.match(moduleSource, /\["dashboard", "Dashboard"\]/);
  assert.match(moduleSource, /\["mfg", "MFG Station Detail"\]/);
  assert.match(moduleSource, /\["nonMfg", "Non-MFG Department Detail"\]/);
  assert.ok(moduleSource.indexOf('["dashboard", "Dashboard"]') < moduleSource.indexOf('["mfg", "MFG Station Detail"]'));
  assert.match(moduleSource, /data-approval-quantity-tab="\$\{id\}"/);
  assert.match(moduleSource, /data-approval-dashboard-request-id/);
  assert.match(moduleSource, /data-approval-dashboard-project/);
  assert.match(moduleSource, /data-approval-dashboard-item/);
  assert.match(moduleSource, /data-approval-dashboard-unit/);
  assert.match(styles, /\.approval-quantity-row-picker/);
  assert.match(styles, /\.approval-quantity-row-chip/);
  assert.match(styles, /\.approval-quantity-chip-action/);
  assert.match(styles, /\.approval-item-unit-matrix-cell-btn/);
  assert.match(app, /renderApprovalQuantityRowPicker/);
  assert.match(app, /panel\.hidden = approvalQuantityReviewTab === "dashboard"/);
  assert.match(app, /function priceReviewDetailScopeForTab/);
  assert.doesNotMatch(app, /function renderProjectItemMatrixOverview/);
  assert.match(app, /function renderPriceReviewItemUnitMatrix/);
  assert.match(html, /Save Direct Edit/);
  assert.match(app, /function saveItemQuantityReviewDirectEdit/);
  assert.match(app, /Item quantity directly edited/);
  assert.match(app, /itemQuantityReviewStatus:\s*"Direct Edit Applied"/);
});

test("Shared evidence renderers keep dashboard and matrix totals reusable", () => {
  assert.match(app, /function renderManagerDemandCostHead/);
  assert.match(app, /function renderManagerDemandCostUnitSummary/);
  assert.match(app, /function managerDemandCostCellImpact/);
  assert.match(app, /function renderManagerDemandCostValue/);
  assert.match(app, /function renderManagerQuantityMatrix/);
  assert.match(app, /function renderManagerQuantityHead/);
  assert.match(app, /function renderPriceReviewCostDashboard/);
  assert.match(app, /function renderPriceReviewStationMatrix/);
  assert.match(app, /function renderApprovedEvidenceAnalysis/);
  assert.match(app, /function managerCarryoverIsApplied/);
  assert.match(app, /function managerCarryoverStatusBucket/);
  assert.match(app, /function managerCarryoverPhaseKey/);
  assert.match(app, /function renderManagerDemandCostCarryoverCompare/);
  assert.match(app, /function renderManagerDemandCostLineCompare/);
  assert.match(app, /function renderManagerCarryoverLedger/);
  assert.match(app, /procurement:carryover-updated/);
  assert.doesNotMatch(app, /<tr class="demand-cost-total-row">/);
  assert.match(app, /MFG Total \/ Non-MFG Department Cost by Selected Phase/);
  assert.match(app, /MFG is all station demand combined/);
  assert.match(app, /demand-cost-unit-head/);
  assert.match(app, /demand-cost-cell-main/);
  assert.match(app, /demand-cost-cell-sub/);
  assert.match(app, /shared-total-highlight/);
  assert.match(app, /quantity-total-head/);
  assert.match(app, /carryover-cell-applied/);
  assert.match(app, /carryover-cell-pending/);
  assert.match(styles, /\.shared-total-highlight/);
  assert.match(styles, /\.carryover-cell-applied/);
  assert.match(styles, /\.demand-cost-cell-sub/);
  assert.match(app, /formatCompactCurrencyFromVnd/);
  assert.match(styles, /width:\s*108px/);
  ["ENG Name", "CN-ENG Name", "VN Name", "Price", "MFG", "FATP TE", "FATP IQC", "FATP PQE", "WH", "Q-LAB", "REL", "ENG1", "ENG2", "ENG3", "IT", "FAC"].forEach((label) => {
    assert.match(app, new RegExp(label.replace(".", "\\.")));
  });
  ["Highest Unit", "Highest Item", "Highest Phase"].forEach((label) => {
    assert.doesNotMatch(app, new RegExp(label));
  });
});

test("Item quantity review popup supports direct edit actions and audit counts", () => {
  assert.match(html, /id="itemQuantityReviewModal"/);
  assert.match(html, /id="itemQuantityReviewSummary"/);
  assert.match(html, /id="itemQuantityReviewBody"/);
  assert.match(html, /data-action="approveItemQuantityReview"/);
  assert.match(html, /data-action="saveItemQuantityReviewDirectEdit"/);
  assert.match(html, /data-action="rejectItemQuantityReview"/);
  assert.match(app, /function openItemQuantityReview/);
  assert.match(app, /function itemQuantityReviewExcelRow/);
  assert.match(app, /data-item-quantity-cell="row-review"/);
  assert.match(app, /data-item-quantity-review-input/);
  assert.match(app, /data-item-quantity-review-mode/);
  assert.match(app, /function addItemQuantityProposalAction/);
  assert.match(app, /function itemQuantityReviewInputChanges/);
  assert.match(app, /aggregateKey/);
  assert.match(app, /function saveItemQuantityReviewDirectEdit/);
  assert.match(app, /syncRowPhaseQtyFromStationBreakdown/);
  assert.match(app, /function rejectItemQuantityReview/);
  assert.match(app, /function approveItemQuantityReview/);
  assert.match(app, /itemQuantityProposalCount/);
  assert.match(app, /itemQuantityRequesterRevisionCount/);
  assert.match(app, /itemQuantityChangeCount/);
  assert.match(app, /Direct Edit Applied/);
  assert.match(app, /save_direct_edit/);
  assert.match(app, /function acceptItemQuantityProposal/);
  assert.match(app, /data-item-quantity-accept-proposal/);
  assert.match(app, /Requester accepted item quantity proposal/);
  assert.match(app, /data-item-quantity-cell="demand-cost"/);
  assert.match(app, /data-item-quantity-cell="station"/);
  assert.match(styles, /\.item-quantity-review-table/);
  assert.match(styles, /\.item-quantity-action-stack/);
  assert.match(styles, /\.item-review-change-stack/);
});

test("Contacts are topbar popup only, not a top-level view", () => {
  const nav = between(html, '<nav class="tabs" aria-label="Main navigation">', "</nav>");
  assert.doesNotMatch(nav, /data-view="contacts"/);
  assert.doesNotMatch(html, /<section class="view" data-view="contacts"/);
  assert.match(html, /data-action="openContactPopup"/);
  assert.match(html, /id="contactPopupModal"/);
  assert.doesNotMatch(app, /function ensureContactsTab/);
  assert.doesNotMatch(app, /function ensureContactsSection/);
  assert.doesNotMatch(app, /function renderContacts/);
  assert.doesNotMatch(app, /setView\("contacts"\)/);
});

test("UAT feedback triage owners are limited to Admin and OM Leader in UI fallback", () => {
  const patchOwner = between(app, "async function patchUatFeedbackOwner", "function omTabLabel");
  assert.match(patchOwner, /uatFeedbackTriageOwners\(\)\.find/);
  assert.match(patchOwner, /Feedback owner must be Admin or OM Leader/);
  const ownerHelper = between(app, "function uatFeedbackTriageOwners", "function omTabLabel");
  assert.match(ownerHelper, /\["admin", "omLeader"\]\.includes\(user\.role\)/);
  assert.match(ownerHelper, /user\.role === "omLeader"/);
  const ownerOptions = between(app, "function uatFeedbackOwnerOptions", "function renderUatFeedbackReview");
  assert.match(ownerOptions, /uatFeedbackTriageOwners\(\)\.forEach/);
  assert.doesNotMatch(ownerOptions, /omAssignees\.forEach/);
  assert.match(server, /Feedback owner must be Admin or OM Leader/);
});

test("Requester workspace uses MFG / Non-MFG Excel worksheet input", () => {
  const departmentView = between(html, '<section class="view active" data-view="department">', '<section class="view" data-view="manager" data-approval-review-role="manager">');
  const opmTabs = between(departmentView, '<div class="inner-tabs" aria-label="Requester workspace sections">', "</div>");
  assert.match(opmTabs, /Request Workspace/);
  assert.match(opmTabs, /Warehouse Inventory/);
  assert.match(opmTabs, /Action Required/);
  assert.match(opmTabs, /Request Status/);
  assert.match(departmentView, /request-workspace-layout/);
  assert.match(departmentView, /Request Worksheet/);
  assert.match(departmentView, /data-request-worksheet-tab="MFG"/);
  assert.match(departmentView, /data-request-worksheet-tab="Non-MFG"/);
  assert.match(departmentView, /id="requestInputContextBar"/);
  assert.match(departmentView, /data-action="openRequestItemPicker"/);
  assert.match(departmentView, />Add Item</);
  assert.match(html, /id="requestItemPickerModal"/);
  assert.match(html, /id="requestItemPickerQuery"/);
  assert.match(html, /id="requestItemPickerLevel1"/);
  assert.match(html, /id="requestItemPickerLevel2"/);
  assert.match(html, /id="requestItemPickerLevel3"/);
  assert.match(html, /data-request-picker-source-tab="catalog"/);
  assert.match(html, /data-request-picker-source-tab="reuse"/);
  assert.match(html, /data-request-picker-source-tab="copy"/);
  assert.match(html, /data-request-picker-source-tab="new"/);
  const pickerModal = between(html, '<div class="modal-backdrop" id="requestItemPickerModal"', '<div class="modal-backdrop" id="contactPopupModal"');
  assert.match(pickerModal, /<th class="picker-col-add">Add<\/th>/);
  assert.match(pickerModal, /<th class="picker-col-item">Item<\/th>/);
  assert.match(pickerModal, /<th class="picker-col-detail">Detail<\/th>/);
  assert.match(pickerModal, /<th class="picker-col-spec">Spec<\/th>/);
  assert.match(pickerModal, /<th class="picker-col-action">Action<\/th>/);
  assert.match(pickerModal, /id="requestCopyDemandPanel"/);
  assert.match(pickerModal, /id="historyPackageSourceProject"/);
  assert.match(pickerModal, /id="historyPackageSourcePhase"/);
  assert.match(pickerModal, /id="historyPackageSourcePackage"/);
  assert.match(pickerModal, /id="historyPackagePreviewCount"/);
  assert.match(pickerModal, /data-action="importHistoryPackage"/);
  assert.match(pickerModal, /<tbody id="historyPackageRows"><\/tbody>/);
  assert.match(pickerModal, /history-package-table/);
  assert.match(pickerModal, /Source Qty/);
  assert.doesNotMatch(pickerModal, /<th[^>]*>Source<\/th>/);
  assert.doesNotMatch(pickerModal, /Phase Trace/);
  assert.doesNotMatch(pickerModal, /PAS Material No/);
  assert.doesNotMatch(pickerModal, /Factory Material No/);
  assert.doesNotMatch(pickerModal, /Vendor Part No/);
  assert.doesNotMatch(pickerModal, /Supplier/);
  assert.doesNotMatch(pickerModal, /OM Assignee/);
  assert.doesNotMatch(pickerModal, /\bFTV\b/);
  assert.match(departmentView, /id="requestPackageNeedDate"/);
  assert.match(departmentView, /id="requestPackageNeedDateLabel"/);
  assert.match(departmentView, /data-action="saveRequesterDraft"/);
  assert.match(departmentView, /data-action="submitRequests"/);
  assert.match(departmentView, /id="requestWorksheetHead"/);
  assert.match(departmentView, /<tbody id="requestRows"><\/tbody>/);
  assert.match(departmentView, /Estimate Variance/);
  assert.match(html, /id="materialEntryStructuredSpec"/);
  assert.match(html, /id="materialEntryUom"/);
  assert.match(html, /id="materialEntryEstimateReason"/);
  assert.match(html, /id="materialEntryDuplicateDifference"/);
  assert.match(html, /id="materialEntryEvidenceReference"/);
  assert.doesNotMatch(departmentView, /id="requestSourcePanel"/);
  assert.doesNotMatch(departmentView, /Source Panel/);
  assert.doesNotMatch(departmentView, /Demand Matrix/);
  assert.doesNotMatch(departmentView, /Demand source modes/);
  assert.doesNotMatch(departmentView, /Selected Matrix Rows/);
  assert.doesNotMatch(departmentView, /id="itemPickerModal"/);
  assert.doesNotMatch(departmentView, /id="requestWorksheetSearch"/);
  assert.doesNotMatch(departmentView, /id="requestWorksheetSourceSelect"/);
  assert.doesNotMatch(departmentView, /id="requestWorksheetAddPhase"/);
  assert.doesNotMatch(departmentView, /Add Demand Lines/);

  assert.match(app, /let requestWorksheetMode = DEMAND_TYPE_MFG/);
  assert.match(app, /function requestWorksheetColumns/);
  assert.match(app, /function requestWorksheetMergedSources/);
  assert.match(app, /function requestItemPickerSources/);
  assert.match(app, /let requestItemPickerLevel1 = ""/);
  assert.match(app, /let requestItemPickerLevel2 = ""/);
  assert.match(app, /let requestItemPickerLevel3 = ""/);
  assert.match(app, /function requestItemPickerLevelValues/);
  assert.match(app, /function requestItemPickerMatchesLevels/);
  assert.match(app, /function syncRequestItemPickerFilters/);
  assert.match(app, /row\.omCategoryLevel1/);
  assert.match(app, /row\.omCategoryLevel2/);
  assert.match(app, /row\.omCategoryLevel3/);
  assert.match(app, /function renderRequestItemPicker/);
  assert.match(app, /function renderHistoryPackageRows/);
  assert.match(app, /function importHistoryPackage/);
  assert.match(app, /requestItemPickerSourceMode === "copy"/);
  assert.match(app, /closeRequestItemPicker\(\)/);
  assert.match(app, /function addWorksheetRow/);
  assert.match(app, /function updateRequestWorksheetQty/);
  assert.match(app, /data-request-worksheet-qty/);
  assert.match(app, /data-request-worksheet-phase/);
  assert.match(app, /data-request-worksheet-column/);
  assert.match(app, /data-request-worksheet-remove/);
  assert.match(app, /data-request-worksheet-tab/);
  assert.match(app, /data-add-worksheet-source/);
  assert.match(app, /requestWorksheetSourceBadge/);
  assert.match(app, /New Item Request from worksheet/);
  assert.match(app, /itemMasterRequestStatus:\s*"Pending Material Review"/);
  assert.match(app, /function materialDuplicateCandidateRows/);
  assert.match(app, /function estimateVarianceDisplayRows/);
  assert.match(app, /detailSection\("Estimate vs PAS Quote", estimateVarianceRows\)/);
  assert.match(app, /compareEstimateToQuote/);
  assert.match(app, /const phases = STAGES/);
  assert.match(app, /requesterPackageRows\(\)/);
  assert.match(app, /requestNeedDateScopeKey/);
  assert.match(app, /requestNeedDateByScope/);
  assert.match(app, /requestRowMatchesSubmitScope/);
  assert.match(app, /requesterSubmitScopeAudit/);
  assert.doesNotMatch(app, /requestContextDemandType/);
  assert.doesNotMatch(app, /requestContextStation/);
  assert.doesNotMatch(pickerModal, /vendor/i);
  assert.doesNotMatch(pickerModal, /supplier/i);
  assert.doesNotMatch(pickerModal, /PAS material no/i);
  assert.doesNotMatch(pickerModal, /factory material no/i);
  assert.doesNotMatch(pickerModal, /OM assignee/i);
  assert.doesNotMatch(pickerModal, /FTV/i);

  const requestWorksheetHeadRenderer = between(app, "function renderRequestWorksheetHead", "function requestInputContextKey");
  assert.match(requestWorksheetHeadRenderer, /requestWorksheetMatrixModule\(\)/);
  assert.match(requestWorksheetHeadRenderer, /renderHead/);
  assert.match(app, /function renderRequestWorksheetPhaseJumpBar/);
  assert.match(app, /function syncRequestWorksheetVisiblePhase/);
  assert.match(app, /function applyRequestWorksheetActiveState/);
  assert.match(app, /data-request-phase-group/);
  assert.match(app, /data-request-phase-jump/);
  assert.match(html, /id="requestWorksheetPhaseJumpBar"/);
  assert.match(html, /id="requestWorksheetCurrentPhaseIndicator"/);

  ["CG", "BG", "FATP", "Test", "Hybrid", "Auto", "ENG Pack", "Zombie", "Laser_pico", "Rework", "Repair", "WH"].forEach((label) => {
    assert.match(app, new RegExp(label.replace("/", "\\/")));
  });
  ["FATP TE", "FATP IQC", "FATP PQE", "Q-LAB", "REL", "ENG1", "ENG2", "ENG3", "IT", "FAC"].forEach((label) => {
    assert.match(app, new RegExp(label.replace("/", "\\/")));
  });

  assert.doesNotMatch(departmentView, /PAS material no/i);
  assert.doesNotMatch(departmentView, /factory material no/i);
  assert.doesNotMatch(departmentView, /vendor/i);
  assert.match(styles, /\.request-worksheet-table[\s\S]*min-width:\s*6900px/);
  assert.match(styles, /\.request-worksheet-shell[\s\S]*border:/);
  assert.match(styles, /\.request-source-badge/);
  assert.match(styles, /\.request-item-picker-card/);
  assert.match(styles, /\.request-item-picker-card[\s\S]*width:\s*min\(1360px,\s*calc\(100vw - 24px\)\)/);
  assert.match(styles, /\.request-item-picker-filterbar/);
  assert.match(styles, /\.request-picker-detail-cell/);
  assert.match(styles, /\.request-picker-spec-cell \.spec-summary[\s\S]*-webkit-line-clamp:\s*3/);
  assert.match(styles, /\.request-phase-jump-row/);
  assert.match(styles, /\.request-phase-jump-bar/);
  assert.match(styles, /\.request-current-phase-indicator/);
  assert.match(styles, /\.request-phase-group-head/);
  assert.match(styles, /\.request-phase-group-head[\s\S]*text-align:\s*center !important/);
  assert.match(styles, /\.request-sticky-col[\s\S]*background:\s*#fff !important/);
  assert.match(styles, /\.request-sticky-col[\s\S]*background-color:\s*#fff !important/);
  assert.match(styles, /\.request-sticky-col[\s\S]*overflow:\s*hidden/);
  assert.match(styles, /\.request-sticky-col[\s\S]*z-index:\s*8/);
  assert.match(styles, /\.request-sticky-right/);
  assert.match(styles, /\.request-sticky-right-action/);
  assert.match(styles, /\.request-sticky-right-hint/);
  assert.match(styles, /\.request-sticky-right-total/);
  assert.match(styles, /\.request-matrix-cell\.active-cell/);
  assert.match(styles, /\.request-item-spec-stack/);
  assert.match(styles, /\.request-spec-divider/);
  assert.match(styles, /\.request-item-spec-stack \.request-spec-summary[\s\S]*-webkit-line-clamp:\s*2/);

  const clickHandler = between(app, 'document.addEventListener("click"', 'document.addEventListener("change"');
  assert.match(clickHandler, /if \(removeWorksheetButton\) \{[\s\S]*removeRequest\(removeWorksheetButton\.dataset\.requestWorksheetRemove\);[\s\S]*\}/);
  assert.match(clickHandler, /if \(removeButton\) \{[\s\S]*showConfirm/);

  assert.match(app, /function renderWarehouseMaintenance/);
  assert.match(app, /function warehouseInventoryRows/);
  assert.match(app, /function warehouseInventoryLedger/);
  assert.match(app, /function warehouseOwnerForTransaction/);
  assert.match(app, /function createWarehouseUseCandidate/);
});

test("Requester item owner and Non-MFG unit rules are explicit", () => {
  assert.match(app, /function isOmOwnedItem/);
  assert.match(app, /function itemOwnerFor/);
  assert.match(app, /function itemOwnerBadgeHtml/);
  ["pda", "data collector", "數據採集器", "zebra", "qr code", "barcode", "monitor", "ipc"].forEach((keyword) => {
    assert.match(app, new RegExp(keyword.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"));
  });
  ["keyboard", "mouse", "hp printer", "scanner stand", "barcode print head", "server", "network", "software"].forEach((keyword) => {
    assert.match(app, new RegExp(keyword.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"));
  });
  const omCatalogRows = between(app, "function omCatalogRows", "function isOmCatalogRow");
  assert.match(omCatalogRows, /\.filter\(isOmOwnedItem\)/);
  const demandUnitHelper = between(app, "function demandUnitOptionsHtml", "function stationBreakdownPhaseKey");
  assert.match(demandUnitHelper, /DEMAND_UNIT_OPTIONS/);
  const draftDemandScopeCell = between(app, "function draftDemandScopeCell", "function requestSourceTraceCell");
  assert.match(draftDemandScopeCell, /<select class="request-unit-select"/);
  assert.doesNotMatch(draftDemandScopeCell, /data-request-demand-unit[^]*<input/);
});

test("Reuse history import carries item identity only and resets target qty", () => {
  const cloneReusableDemandRows = between(app, "function cloneReusableDemandRows", "function reusableReferenceFields");
  assert.match(cloneReusableDemandRows, /phase:\s*targetPhase/);
  assert.match(cloneReusableDemandRows, /demandType\s*=\s*lastDemandType/);
  assert.match(cloneReusableDemandRows, /station\s*=\s*itemPickerStation/);
  assert.match(cloneReusableDemandRows, /demandUnit\s*=\s*itemPickerDemandUnit/);
  assert.doesNotMatch(cloneReusableDemandRows, /phase:\s*stationBreakdownPhaseKey\(item\)\s*\|\|\s*targetPhase/);
  const requestFromRecord = between(app, "function requestFromRecord", "function suggestionToRecord");
  assert.match(requestFromRecord, /const draft = \{/);
  assert.match(requestFromRecord, /normalizeRequestDemandDepartment\(draft, demandDepartment\)/);
  assert.match(requestFromRecord, /requesterDept/);
  assert.match(requestFromRecord, /demandDepartment/);
  const phaseQtySummary = between(app, "function phaseQtySummary", "function historyPackageKey");
  assert.match(phaseQtySummary, /stationBreakdownPhaseTotal\(row,\s*stage\)/);
  assert.match(app, /historyRequestOverrides\(row,\s*false,\s*context\)/);
  assert.match(app, /Source quantity kept as reference only/);
  assert.match(app, /Qty starts at 0/);
  const reusableReferenceFields = between(app, "function reusableReferenceFields", "function historyRequestOverrides");
  assert.match(reusableReferenceFields, /const sourceLine = sourceLineForHistory\(record\)/);
  assert.match(reusableReferenceFields, /sourceLine,/);
});

test("Reuse by Item history rows keep requester-safe source, item, and spec in separate columns", () => {
  const renderHistoryRows = between(app, "function renderHistoryRows", "function omUserQuoteDecisionLabel");
  assert.match(renderHistoryRows, /history-source-project/);
  assert.doesNotMatch(renderHistoryRows, /history-po-no/);
  assert.doesNotMatch(renderHistoryRows, /history-material-no/);
  assert.match(renderHistoryRows, /history-item-name/);
  assert.match(renderHistoryRows, /history-spec/);
  assert.match(renderHistoryRows, /\$\{row\.project \|\| "-"\}/);
  assert.doesNotMatch(renderHistoryRows, /\$\{factoryMaterialNoFor\(row\) \|\| "Factory material no pending"\}/);
  assert.match(renderHistoryRows, /<td colspan="6" class="empty-cell">/);
  assert.match(app, /function addHistoryRecord\(recordId,\s*useSourceQty = false\)/);
  assert.match(app, /Quantity starts at 0/);
});

test("Cost calculation uses USD canonical with VND display conversion", () => {
  assert.match(app, /function amountUsdFromVnd/);
  assert.match(app, /function amountVndFromUsd/);
  assert.match(app, /function formatMoneyFromUsd/);
  assert.match(app, /function formatMoneyFromVnd/);
  assert.match(app, /function legacyPriceToUsd/);
  assert.match(app, /function formatCompactCurrencyFromUsd/);
  assert.match(app, /function managerQuantityPriceCandidate/);
  assert.match(app, /unitPriceUsd/);
  assert.match(app, /updatedPriceUsd/);
  assert.match(app, /estimatedUnitPriceUsd/);
  assert.match(app, /estimatedAmountUsd/);
  assert.match(app, /function effectiveUnitPrice\(row\) \{\s*return legacyPriceToUsd\(row, "updatedPrice"\) \|\| legacyPriceToUsd\(row, "unitPrice"\);/);
  assert.match(app, /timestampPatch\.updatedPriceUsd = normalizedValue/);
  assert.match(app, /timestampPatch\.updatedPriceVnd = clampQty\(value\)/);
  assert.match(app, /formatCompactCurrencyFromUsd\(managerDemandCostAmount/);
  assert.match(app, /event\.target\.id === "currencyDisplaySelect"[\s\S]*renderPriceReview\(\)/);
});

test("Shared table and button layout standard is enforced", () => {
  assert.match(styles, /\.table-shell/);
  assert.match(styles, /\.table-fixed/);
  assert.match(styles, /\.cell-text/);
  assert.match(styles, /\.cell-spec/);
  assert.match(styles, /\.cell-number/);
  assert.match(styles, /\.cell-action/);
  assert.match(styles, /\.cell-timeline/);
  assert.match(styles, /\.form-table/);
  assert.match(styles, /\.dense-dashboard-table/);
  assert.match(styles, /\.workflow-table/);
  assert.match(styles, /\.matrix-table/);
  assert.match(styles, /\.horizontal-table-nav/);
  assert.match(styles, /\.horizontal-table-nav__group/);

  const departmentView = between(html, '<section class="view active" data-view="department">', '<section class="view" data-view="manager" data-approval-review-role="manager">');
  assert.match(departmentView, /table-shell form-table-shell/);
  assert.match(departmentView, /data-horizontal-nav="requestWorksheet"/);
  assert.match(departmentView, /data-table table-fixed form-table matrix-table request-table request-worksheet-table/);
  assert.match(departmentView, /data-layout-managed="manual"/);
  assert.doesNotMatch(departmentView, /data-table table-fixed form-table search-table/);
  assert.doesNotMatch(departmentView, /history-item-table/);

  const analysis = between(html, 'data-manager-panel="analysis"', 'data-manager-panel="setup"');
  assert.match(analysis, /table-wrap table-shell demand-cost-wrap/);
  assert.match(analysis, /data-horizontal-nav="managerDemandCost"/);
  assert.match(analysis, /data-table table-fixed dense-dashboard-table demand-cost-table/);

  assert.doesNotMatch(app, />Add Item to Request<\/button>/);
  assert.doesNotMatch(app, /data-edit-demand="[^"]*"[^>]*>Edit Demand<\/button>/);
  assert.match(app, /class="[^"]*cell-action/);
  assert.match(app, /class="[^"]*cell-spec/);
  assert.match(app, /class="cell-timeline"/);
  assert.match(app, /cell-spec-clamp/);
  assert.match(app, /data-add-worksheet-source/);
});

test("v1.3 layout contract prevents recurring table and button regressions", () => {
  const departmentView = between(html, '<section class="view active" data-view="department">', '<section class="view" data-view="manager" data-approval-review-role="manager">');
  assert.match(styles, /v1\.3 final layout authority/);
  assert.match(styles, /v2\.0 adaptive operation layout authority/);
  assert.match(styles, /body\s*\{[\s\S]*overflow-x:\s*hidden/);
  assert.match(styles, /\.request-workspace-layout\s*\{[\s\S]*display:\s*block/);
  assert.match(styles, /\.request-worksheet-table\.matrix-table[\s\S]*min-width:\s*6900px !important/);
  assert.match(styles, /\.request-worksheet-commandbar/);
  assert.match(styles, /\.request-source-badge/);
  assert.doesNotMatch(departmentView, /requestSourcePanel/);
  assert.match(styles, /\.carryover-suggestions-panel/);
  assert.match(styles, /\.carryover-suggestion-card/);
  assert.doesNotMatch(departmentView, /previousLineRows/);
  assert.match(styles, /\.request-item-picker-table/);
  assert.match(styles, /\.cell-action[\s\S]*width:\s*76px !important/);
  assert.match(styles, /\.demand-cost-table[\s\S]*width:\s*max-content/);
  assert.match(styles, /\.demand-cost-table[\s\S]*min-width:\s*1720px/);
  assert.match(styles, /\.demand-cost-cell-btn[\s\S]*text-overflow:\s*clip/);
  assert.match(styles, /\.om-rate-utility[\s\S]*width:\s*max-content/);
  assert.match(styles, /\.om-rate-utility \.om-rate-save[\s\S]*min-width:\s*72px !important/);
  assert.match(styles, /\.request-matrix-input[\s\S]*width:\s*64px/);
  const requestWorksheetHeadRenderer = between(app, "function renderRequestWorksheetHead", "function requestInputContextKey");
  assert.match(requestWorksheetHeadRenderer, /requestWorksheetMatrixModule\(\)/);
  assert.doesNotMatch(requestWorksheetHeadRenderer, /request-col-detail/);
  assert.match(styles, /\.request-col-actions[\s\S]*width:\s*118px/);
  assert.doesNotMatch(styles, /\.request-table th:nth-child\(10\)/);
  assert.match(styles, /\.demand-editor-table th:last-child[\s\S]*position:\s*sticky\s*!important/);
  assert.match(styles, /\.demand-cost-wrap,[\s\S]*?\.quantity-matrix-wrap,[\s\S]*?overflow-x:\s*auto/);
  assert.match(styles, /@media \(max-width:\s*1100px\)/);
  assert.match(styles, /@media \(max-width:\s*760px\)/);
  assert.doesNotMatch(app, />Add Item to Request<\/button>/);
  assert.doesNotMatch(app, />Edit Demand<\/button>/);
  assert.ok(fs.existsSync("tests/layout-smoke.js"));
  const layoutSmoke = fs.readFileSync("tests/layout-smoke.js", "utf8");
  assert.match(layoutSmoke, /assertNoPageOverflow/);
  assert.match(layoutSmoke, /assertButtonsStayInsideCells/);
  assert.match(layoutSmoke, /assertVisibleTableCellsDoNotOverlap/);
  assert.match(layoutSmoke, /Responsive \$\{viewport\.label\} requester worksheet/);
  assert.match(layoutSmoke, /width:\s*760/);
  const testScript = fs.readFileSync("test.sh", "utf8");
  assert.match(testScript, /tests\/layout-smoke\.js/);
  assert.match(testScript, /Layout smoke skipped: Playwright is not installed/);
});

test("Need Date and DRI price review layer are wired", () => {
  const priceReviewRequiresBudgetApprover = between(app, "function priceReviewRequiresBudgetApprover", "function priceReviewPendingOwner");
  const priceReviewPendingRowsForRole = between(app, "function priceReviewPendingRowsForRole", "function priceReviewHistoryRows");
  const applyPriceReviewDecision = between(app, "function applyPriceReviewDecision", "function roleOptionsHtml");
	  const isPriceReviewReworkRequired = between(app, "function isPriceReviewReworkRequired", "function canOmAskUserAAmend");
	  const isOmRejectReworkRequired = between(app, "function isOmRejectReworkRequired", "function canOmAskUserAAmend");
	  const needConfirmationRows = between(app, "function needConfirmationRows", "function userQuoteAmountLabel");
	  const renderNeedConfirmationRows = between(app, "function renderNeedConfirmationRows", "function compactTimestamp");

  assert.match(html, /Employee ID \/ Account/);
  assert.match(html, /id="loginAccountInput"/);
  assert.match(html, /value="123"/);
  assert.match(html, /requester-responsibility-data\.js/);
  assert.match(app, /function findRequesterPersonaByIdentifier/);
  assert.match(app, /REQUESTER_RESPONSIBILITY_MASTER/);
  const loginForm = between(html, '<form class="login-card" id="loginForm">', "</form>");
  assert.match(loginForm, /<option value="requester">Requester<\/option>[\s\S]*<option value="dri">Dept DRI<\/option>[\s\S]*<option value="omLeader">OM Leader \(Mai\)<\/option>[\s\S]*<option value="omMember">OM Purchasing \(Giang \/ Linh\)<\/option>/);
  assert.match(loginForm, /id="omOperatorField"/);
  assert.match(loginForm, /id="omOperatorSelect"/);
  assert.match(loginForm, /<option value="projectDri">Budget Approver<\/option>/);
  assert.match(loginForm, /<option value="buyer">Buyer Handoff<\/option>/);
  assert.match(loginForm, /<option value="admin">Admin<\/option>/);
  assert.doesNotMatch(loginForm, /MFG Coordinator|Sourcing|Buyer PR \/ PO|Project DRI|User A/);
  assert.doesNotMatch(html, /Manager B/);
  assert.doesNotMatch(app, /Manager B/);
  assert.doesNotMatch(server, /Manager B/);
  assert.match(html, /<option value="requester">Requester<\/option>/);
  assert.doesNotMatch(html, /<option value="requester">OPM \/ DRI Requester<\/option>/);
  assert.match(html, /<option value="dri">Dept DRI<\/option>/);
  assert.match(html, /<option value="projectDri">Budget Approver<\/option>/);
  assert.match(html, /data-view="priceReview"/);
  assert.doesNotMatch(html, /Approved Analysis/);
  assert.match(app, /priceReviewTabs:\s*\["pending", "history"\]/);
  assert.match(app, /pending:\s*"Dept Review"/);
  assert.match(app, /pending:\s*"Budget Review"/);
  assert.match(approvalReviewSurfaceModule, /tabs:\s*REVIEW_HISTORY_TABS/);
  assert.doesNotMatch(approvalReviewSurfaceModule, /projectReview:\s*"Project Review"/);
  assert.match(html, /Review History/);
  assert.match(html, /id="priceReviewQueueTabs"/);
  assert.match(app, /Submission Review/);
  assert.match(app, /Price Exception Review/);
  assert.match(app, /Stock \/ Carryover Review/);
  assert.match(app, /Budget Exception Approval/);
  assert.doesNotMatch(html, /data-price-review-tab="costDashboard"/);
  assert.doesNotMatch(html, /data-price-review-tab="stationMatrix"/);
  assert.match(html, /data-price-review-panel="projectReview"/);
  assert.match(html, /id="priceReviewApprovedAnalysis"/);
  assert.match(html, /id="priceReviewInlineAnalysis"/);
  assert.match(html, /Project Context/);
  assert.doesNotMatch(html, /Project Review Evidence/);
  assert.doesNotMatch(html, /Project Item Matrix Overview/);
  assert.doesNotMatch(html, /Item Unit Matrix/);
  assert.match(html, />Dashboard</);
  assert.match(html, /Single project all-items MFG \/ Non-MFG dashboard/);
  assert.match(html, /MFG Station Detail/);
  assert.match(html, /Non-MFG Department Detail/);
  assert.match(html, /data-approval-quantity-tab="mfg"/);
  assert.match(html, /data-approval-quantity-tab="nonMfg"/);
  assert.match(html, /data-approval-quantity-tab="dashboard"/);
  assert.match(html, /id="priceReviewInlineDemandCostRows"/);
  assert.match(app, /function renderPriceReviewCostDashboard/);
  assert.doesNotMatch(app, /function renderProjectItemMatrixOverview/);
  assert.match(app, /function renderPriceReviewItemUnitMatrix/);
  assert.match(app, /renderDashboardParts/);
  assert.match(app, /approvalQuantityMatrixRows\(dashboardSourceRows\)/);
  assert.match(app, /function projectContextSwitcherHtml/);
  assert.match(app, /data-project-context-project/);
  assert.match(app, /function applyProjectContextSwitch/);
  assert.match(styles, /\.project-context-switcher/);
  assert.match(styles, /\.project-context-chip\.active/);
  assert.match(app, /function approvalQuantityLineSummary/);
  assert.match(app, /function approvalPipelineStatus/);
  assert.match(app, /function approvalPipelineDetailHtml/);
  assert.match(app, /Approval \/ Pipeline Detail/);
  assert.match(app, /data-approval-pipeline-status/);
  assert.match(styles, /\.approval-pipeline-pending/);
  assert.match(styles, /\.approval-pipeline-current/);
  assert.match(app, /itemMeta:\s*approvalQuantityLineSummary\(request\)/);
  assert.match(app, /Mainline:\s*"MFG Mainline Station"/);
  assert.match(app, /"Demand Unit":\s*"Non-MFG Department"/);
  assert.match(app, /currencyDisplay/);
  assert.match(app, /function renderPriceReviewStationMatrix/);
  assert.match(app, /function renderManagerDemandCostDashboard/);
  assert.match(app, /function renderManagerQuantityMatrix/);
  assert.match(app, /currentRole === "dri"[\s\S]*Item Switcher/);
  assert.doesNotMatch(app, /workspace\.hidden = isDeptDriPendingReview/);
  assert.doesNotMatch(app, /workspace\.innerHTML = ""/);
  assert.match(app, /function normalizeRequestDemandDepartment/);
  assert.match(app, /row\.demandUnit && normalizeQuantityDashboardUnit\(row\.demandUnit\) !== "MFG"/);
  assert.match(app, /station:\s*demandType === DEMAND_TYPE_MFG/);
  assert.match(app, /demandUnit:\s*demandType === DEMAND_TYPE_MFG \? "" : demandUnitFor\(entry\)/);
  assert.match(app, /function rowDemandDepartment/);
  assert.match(app, /const entryDemandDepartment = rowDemandDepartment\(entry, demandDepartment\)/);
  assert.match(app, /requesterDept: entry\.requesterDept \|\| entryDemandDepartment/);
  assert.match(app, /demandDepartment: entry\.demandDepartment \|\| entryDemandDepartment/);
  assert.match(app, /data-item-quantity-request/);
  assert.match(app, /item-quantity-compact-summary/);
  assert.match(styles, /\.demand-cost-col-request/);
  assert.match(html, /approval-quantity-review\.js/);
  assert.doesNotMatch(app, /function renderApprovalQuantityReviewWorkspace/);
  const priceReviewInlineAnalysis = between(html, 'id="priceReviewInlineAnalysis"', 'data-price-review-panel="projectReview"');
  const priceReviewApprovedAnalysis = between(html, 'id="priceReviewApprovedAnalysis"', 'data-price-review-panel="history"');
  assert.doesNotMatch(priceReviewInlineAnalysis, /Confirmed Carryover Saving/);
  assert.doesNotMatch(priceReviewInlineAnalysis, /Line Carryover Impact/);
  assert.doesNotMatch(priceReviewInlineAnalysis, /Carryover Ledger/);
  assert.doesNotMatch(priceReviewApprovedAnalysis, /Confirmed Carryover Saving|Line Carryover Impact|Carryover Ledger/);
  assert.match(html, /data-view="adminSetup"/);
  assert.match(html, /Access & Approval Setup/);
  assert.match(html, /User Lifecycle/);
  assert.match(html, /Roles & Permissions/);
  assert.match(html, /Sensitive Field Access/);
  assert.match(html, /Audit Log/);
  assert.match(html, /History Price Delta Threshold \(USD\)/);
  assert.match(html, /OM Assignment Rules/);
  assert.match(html, /data-action="createOmAssignmentRule"/);
  assert.match(html, /id="adminOmAssignmentRuleRows"/);
  assert.match(html, /data-action="createAdminUser"/);
  assert.match(html, /data-action="importAdminUsers"/);
  assert.match(html, /data-action="exportAdminUsers"/);
  assert.doesNotMatch(html, /Computer Threshold %/);
  assert.doesNotMatch(html, /MFG Threshold %/);
  assert.match(app, /Need Date is required/);
  assert.match(app, /requestPackageNeedDate/);
  assert.match(app, /requestPackageNeedDateValue/);
  assert.match(app, /currentRequestScopeNeedDate/);
  assert.match(app, /function renderPriceReview/);
  assert.match(app, /function renderPriceReviewAnalysis/);
  assert.match(app, /function renderPriceReviewInlineAnalysis/);
  assert.match(app, /const visible = isPriceReviewInlineAnalysisRole\(\) && currentPriceReviewTab === "pending"/);
  assert.match(app, /function priceReviewSelectedRowScope/);
  assert.match(app, /function priceReviewScopedAnalysisRows/);
  assert.match(app, /function priceReviewAnalysisRows/);
  assert.match(app, /function updatePriceReviewAnalysisScopeLabel/);
  assert.match(app, /function updatePriceReviewInlineScopeLabel/);
  assert.match(app, /function applyPriceReviewDecision/);
  assert.match(app, /function priceReviewRequiresBudgetApprover/);
  assert.match(app, /DEPT_DRI_SUBMISSION_PENDING/);
  assert.match(app, /function isDeptDriSubmissionPending/);
  assert.match(app, /function omLeaderIntakeRoutingPatch/);
  assert.match(app, /Submitted to Dept DRI/);
  assert.doesNotMatch(app, /Dept DRI approved\. Row moved to OM Leader Export Package queue/);
  assert.doesNotMatch(app, /Dept DRI approved\. Row moved to OM Export Package queue/);
  assert.match(app, /Waiting Budget Approver/);
  assert.match(app, /function saveAdminApprovalSetup/);
  assert.match(app, /function createAdminUserFromForm/);
  assert.match(app, /function updateAdminRolePermission/);
  assert.match(app, /function updateAdminFieldVisibility/);
  assert.match(app, /function exportAdminAuditLog/);
  assert.match(app, /clearPriceReviewDemandCostFilters/);
  assert.match(app, /clearPriceReviewQuantityFilters/);
  assert.match(app, /PRICE_AUTO_CLEARED/);
  assert.match(app, /PRICE_ESCALATION_REQUIRED/);
  assert.match(app, /USER_CONFIRMATION_NOT_REQUIRED/);
  assert.match(app, /Auto cleared by threshold/);
  assert.match(app, /Price escalation required/);

  assert.match(priceReviewRequiresBudgetApprover, /row\?\.priceDecisionStatus === PRICE_ESCALATION_REQUIRED/);
  assert.match(priceReviewRequiresBudgetApprover, /isTemporaryBudgetRequest\(row\)/);
  assert.doesNotMatch(priceReviewRequiresBudgetApprover, /^\s*return\s+isTemporaryBudgetRequest\(row\);\s*$/m);
  assert.match(app, /COST_MANAGER_AUTH_PENDING/);
  assert.match(app, /function applyCostManagerAuthorization/);
  assert.match(app, /data-cost-manager-authorization/);
  assert.match(app, /Dept DRI approved\. Waiting Cost Manager authorization/);
  assert.match(app, /function priceReviewSubmissionRows/);
  assert.match(app, /function priceReviewExceptionRows/);
  assert.match(app, /function priceReviewBudgetRows/);
  assert.match(app, /function priceReviewStockRows/);
  assert.match(app, /function availablePriceReviewQueues/);
  assert.match(app, /currentRole === "dri"/);
  assert.match(app, /currentRole === "projectDri"/);
  assert.match(app, /data-price-review-queue/);
  assert.match(app, /priceReviewTabs: \["pending", "history"\]/);
  const budgetApproverWorkspaceConfig = between(app, '  projectDri: {\n    mainViews: ["priceReview"],', '  buyer: {');
  assert.match(budgetApproverWorkspaceConfig, /priceReviewTabs: \["pending", "history"\]/);
  assert.doesNotMatch(budgetApproverWorkspaceConfig, /costDashboard|stationMatrix/);
  assert.match(app, /function approvedRowsForRole/);
  assert.match(app, /function priceReviewProjectRowsForRole/);
  assert.match(app, /<th>Sent To<\/th>/);
  assert.match(app, /<th>Current Owner<\/th>/);
  assert.match(app, /<th>PO Status<\/th>/);
  assert.match(app, /data-price-review-select-row/);
  assert.match(app, /shouldScrollPriceReviewInlineAnalysis/);
  assert.match(app, /scrollIntoView\(\{ behavior: "smooth", block: "start" \}\)/);
  assert.match(app, /function preserveApprovalViewport/);
  assert.match(app, /function restoreApprovalViewport/);
  assert.match(applyPriceReviewDecision, /preserveApprovalViewport\("priceReview"/);
  assert.match(applyPriceReviewDecision, /currentRole === "admin"/);
  assert.match(applyPriceReviewDecision, /Admin manages setup only and cannot approve business price reviews/);
  assert.match(applyPriceReviewDecision, /priceReviewReworkRequired:\s*true/);
  assert.match(applyPriceReviewDecision, /Price escalation rejected\. Row returned to Requester Action Required/);
	  assert.match(isPriceReviewReworkRequired, /Boolean\(row\?\.priceReviewReworkRequired\)/);
	  assert.match(isPriceReviewReworkRequired, /row\.priceApprovalStatus === PRICE_ESCALATION_REJECTED/);
	  assert.match(isPriceReviewReworkRequired, /row\.priceDecisionStatus === PRICE_ESCALATION_REJECTED/);
	  assert.match(isOmRejectReworkRequired, /omRejectReworkRequired/);
	  assert.match(isOmRejectReworkRequired, /OM_REJECTED_TO_DRI/);
	  assert.match(needConfirmationRows, /isPriceReviewReworkRequired\(row\)/);
	  assert.match(needConfirmationRows, /isOmRejectReworkRequired\(row\)/);
	  assert.match(renderNeedConfirmationRows, /Price \/ Budget Review Rejected/);
	  assert.match(renderNeedConfirmationRows, /OM Rework Required/);
  assert.match(roleGuards, /admin\.mapping/);
  assert.match(roleGuards, /admin\.user_scope/);
  assert.match(roleGuards, /scopeMode === "priceReviewScoped"/);
  assert.ok(fs.existsSync("app-modules/horizontal-table-navigator.js"));
  assert.ok(fs.existsSync("app-modules/request-worksheet-matrix.js"));
  assert.ok(fs.existsSync("app-modules/approval-workbench.js"));
  assert.ok(fs.existsSync("app-modules/role-queue-config.js"));
	});

test("OM tabs and PAS quote result contract are consolidated", () => {
  const omView = between(html, '<section class="view" data-view="om">', '<section class="view" data-view="buyer">');
  assert.match(omView, /Submission Dashboard/);
  assert.match(omView, /PAS Demand No/);
  assert.match(omView, /PAS Quote Result/);
  assert.match(omView, /Export Package/);
  assert.match(omView, /OM UAT Feedback/);
  assert.match(omView, /data-action="openPageFeedback"/);
  assert.doesNotMatch(omView, /data-om-tab="uatFeedback"/);
  assert.doesNotMatch(omView, /data-om-panel="uatFeedback"/);
  assert.match(omView, /data-om-tab="quoteExpiry"/);
  assert.match(omView, /data-om-panel="quoteExpiry"/);
  assert.match(omView, /Quote Expiry Monitor/);
  assert.match(omView, /class="mini approve om-rate-save"/);
  assert.match(omView, /om-rate-utility/);
  assert.match(styles, /\.om-rate-grid \.om-rate-save/);
  assert.match(styles, /min-width:\s*84px/);
  assert.match(omView, /Submitted \/ Received Date/);
  assert.match(omView, /Pending Owner/);
  assert.match(omView, /Days Pending/);
  const omSubmissionTable = between(omView, 'id="omSubmissionTable"', '</table>');
  assert.doesNotMatch(omSubmissionTable, /<th>Quote Status<\/th>/);
  assert.doesNotMatch(omSubmissionTable, /<th>Estimated ETA<\/th>/);
  assert.doesNotMatch(omSubmissionTable, /<th>Next Action<\/th>/);
  assert.doesNotMatch(omSubmissionTable, /<th>Buyer Days<\/th>/);
  assert.doesNotMatch(app, /function omEtaCell/);
  assert.doesNotMatch(app, /function omNextActionCell/);
  assert.doesNotMatch(app, /function omBuyerDaysCell/);
  assert.match(app, /function omPendingOwnerHelper/);
  assert.doesNotMatch(omView, /<th>Budget Progress<\/th>/);
  assert.doesNotMatch(omView, /<th>PR Progress<\/th>/);
  assert.doesNotMatch(omView, /<th>PO Progress<\/th>/);
  assert.doesNotMatch(omView, /<th>Arrived Progress<\/th>/);
  assert.doesNotMatch(omView, /<th>Key Dates<\/th>/);
  assert.match(app, /function omPendingOwnerForRow/);
  assert.match(app, /function omQuoteStatusForRow/);
  assert.match(app, /function isOmExportAuthorized/);
  assert.match(app, /Only Requester confirmed or price-cleared rows can be prepared/);
  assert.match(workflowStatusModule, /return "Buyer Handoff"/);
  assert.match(workflowStatusModule, /Buyer owns PR \/ PO after OM export/);
  assert.match(app, /workflowStatusForRow\(row, "om"\)\.pendingOwner/);
  assert.doesNotMatch(between(app, "function omNextActionForGroup", "function renderOmSubmissionExpiryMonitor"), /Downstream/);
  const pasDemandTable = between(omView, 'data-om-panel="pasRequest"', 'data-om-panel="quoteConfirm"');
  assert.match(pasDemandTable, /om-pas-demand-table/);
  assert.match(pasDemandTable, /<th>CPD-IEP Owner<\/th>/);
  assert.match(pasDemandTable, /<th>Assigned To<\/th>/);
  assert.match(pasDemandTable, /<th>PAS Demand No<\/th>/);
  assert.doesNotMatch(pasDemandTable, /<th>Item Context<\/th>/);
  assert.doesNotMatch(pasDemandTable, /<th>Level 2 \/ Level 3<\/th>/);
  assert.match(app, /function pasDemandNoEntryHtml/);
  assert.match(app, /data-om-field="pasDemandNo"/);
  assert.match(app, /Enter PAS Demand No first/);
  assert.match(app, /updateOmField\(requestId, "pasDemandNo", typedDemandNo\)/);
  const quoteTable = between(omView, 'data-om-panel="quoteConfirm"', 'data-om-panel="quoteExpiry"');
  assert.match(quoteTable, /om-quote-result-table/);
  assert.match(quoteTable, /om-quote-col-project/);
  assert.match(quoteTable, /om-quote-col-material/);
  assert.match(quoteTable, /om-quote-col-actions/);
  [
    "Project",
    "Phase",
    "Item / Spec",
    "Qty",
    "PAS Demand No",
    "PAS Material No",
    "Vendor",
    "Vendor Code",
    "Unit Price",
    "Currency",
    "Quote Date",
    "Valid Until",
    "Files",
    "Completion / Missing",
    "Assigned To",
    "Actions",
    "Detail",
  ].forEach((label) => assert.match(quoteTable, new RegExp(`<th[^>]*>${label.replace("/", "\\/")}<\\/th>`)));
  assert.match(quoteTable, /<th[^>]*>Assigned To<\/th>/);
  assert.doesNotMatch(quoteTable, /<th>PAS Tracking<\/th>/);
  assert.doesNotMatch(quoteTable, /<th>Quote Result<\/th>/);
  assert.doesNotMatch(quoteTable, /<th>Quote Validity<\/th>/);
  assert.match(app, /Quote Valid Until/);
  assert.match(app, /Quote Screenshot/);
  assert.match(app, /Vendor Name/);
  assert.match(app, /Vendor Code/);
  assert.match(app, /data-om-price-currency/);
  assert.match(app, /title="Save Quote Info"/);
  assert.match(app, /title="Send to User A"/);
  assert.match(app, /omQuoteResultReadOnlyReason/);
  assert.doesNotMatch(app, /Upload PDF/);
  assert.doesNotMatch(app, /Quote PDF/);
  const quoteExpiryTable = between(omView, 'data-om-panel="quoteExpiry"', 'data-om-panel="finalExport"');
  assert.match(quoteExpiryTable, /<th>Quote Valid Until<\/th>/);
  assert.match(quoteExpiryTable, /<th>Days Left<\/th>/);
  assert.match(quoteExpiryTable, /<th>Expiry Status<\/th>/);
  assert.match(quoteExpiryTable, /<th>Assigned To<\/th>/);
  assert.match(quoteExpiryTable, /<th>Next Action<\/th>/);
  assert.doesNotMatch(quoteExpiryTable, /data-om-field="quoteValidUntil"/);
  assert.doesNotMatch(quoteExpiryTable, /data-om-row-button-action="exportPackage"/);
  assert.match(app, /currentOmTab = "submission"/);
  assert.match(app, /allowedTabs\.has\(tabName\) \? tabName : "submission"/);
  const exportPanel = between(html, 'data-om-panel="finalExport"', '<section class="view" data-view="buyer">');
  assert.match(exportPanel, /<th>Assigned To<\/th>/);
  assert.match(exportPanel, /Cost Type \/ Target/);
  assert.doesNotMatch(app, />Export Excel<\/button>/);
  assert.doesNotMatch(app, />Export Quote PDF Package<\/button>/);
  assert.match(app, /Export Package/);
  assert.match(app, /Expense → ECS \/ Capex → CFA/);
  assert.match(app, /editableMaterialNo: false/);
});

test("UAT feedback is a utility page and row detail action, not an OM workflow tab", () => {
  assert.match(html, /data-view="uatFeedbackReview" data-roles="omLeader omMember admin"/);
  assert.match(html, /data-action="openUatFeedbackReview"/);
  assert.match(html, /My Feedback/);
  assert.match(html, /id="uatFeedbackReviewTitle"/);
  assert.match(html, /id="uatFeedbackReviewHelper"/);
  assert.match(html, /id="uatFeedbackModal"/);
  assert.match(html, /id="uatFeedbackForm"/);
  assert.match(html, /id="uatFeedbackScreenshot"/);
  assert.match(app, /screenshotFileName/);
  assert.match(app, /function createUatFeedback/);
  assert.match(app, /POST", body: payload/);
  assert.match(app, /\/api\/uat-feedback\/my/);
  assert.match(app, /\/api\/uat-feedback"/);
  assert.match(app, /function renderUatFeedbackReview/);
  assert.match(app, /function uatRowFeedbackSection/);
  assert.match(app, /data-uat-row-feedback/);
  assert.match(app, /if \(name === "uatFeedbackReview"\)/);
  assert.match(app, /refreshUatFeedback\(\{ review: isUatFeedbackReviewer\(\), silent: true \}\)/);
  assert.match(app, /isUatFeedbackReviewer/);
  assert.match(app, /My UAT Feedback Status/);
  assert.match(app, /Read Only/);
  const omView = between(html, '<section class="view" data-view="om">', '<section class="view" data-view="uatFeedbackReview">');
  assert.doesNotMatch(omView, /<th>Feedback<\/th>/);
});

test("Admin console surfaces live UAT feedback and screenshot downloads", () => {
  const adminView = between(html, '<section class="view" data-view="adminSetup">', '<section class="view" data-view="buyer">');
  assert.match(adminView, /Admin Console/);
  assert.match(adminView, /id="adminConsoleSummary"/);
  assert.match(adminView, /id="adminConsoleFeedbackRows"/);
  assert.match(adminView, /data-action="refreshAdminConsole"/);
  assert.match(adminView, /attached screenshots/);
  assert.match(app, /function renderAdminConsole/);
  assert.match(app, /admin-feedback-full/);
  assert.match(app, /function refreshAdminConsole/);
  assert.match(app, /screenshotAttachmentId/);
  assert.match(app, /uatFeedbackEvidenceHtml\(row\)/);
  assert.match(app, /refreshUatFeedback\(\{ review: true, silent: false \}\)/);
  assert.match(server, /JSON\.parse\(metadata\)/);
});

test("Admin UI surfaces SAP PO Raw import preview and UAT commit controls", () => {
  const adminView = between(html, '<section class="view" data-view="adminSetup">', '<section class="view" data-view="buyer">');
  assert.match(adminView, /SAP PO Raw Import/);
  assert.match(adminView, /id="sapPoRawWorkbookPath"/);
  assert.match(adminView, /id="sapPoRawScopeMode"/);
  assert.match(adminView, /data-action="previewSapPoRawImport"/);
  assert.match(adminView, /data-action="commitSapPoRawImport"/);
  assert.match(adminView, /id="sapPoRawImportSummary"/);
  assert.match(adminView, /id="sapPoRawImportRows"/);
  assert.match(app, /function renderSapPoRawImportPanel/);
  assert.match(app, /function previewSapPoRawImportFromForm/);
  assert.match(app, /function commitSapPoRawImportFromPreview/);
  assert.match(app, /refreshSapPoRawImportStatus\(\{ silent: true \}\)/);
});

test("MySQL API Phase 1 and OM assignment contract are present", () => {
  assert.match(server, /\/api\/login/);
  assert.match(server, /function findUserByIdentifier/);
  assert.match(server, /employee_id/);
  assert.match(server, /Invalid account or password/);
  assert.match(server, /\/api\/logout/);
  assert.match(server, /\/api\/me/);
  assert.match(server, /\/api\/om\/assignees/);
  assert.match(server, /\/api\/om\/assignments/);
  assert.match(server, /api\\\/om\\\/requests\\\/\(\[\^\/\]\+\)\\\/assign/);
  assert.match(server, /mysql2\/promise/);
  assert.match(server, /process\.env\.DB_HOST/);
  assert.match(server, /process\.env\.DB_PORT/);
  assert.match(server, /process\.env\.DB_NAME/);
  assert.match(server, /function loadLocalEnv/);
  assert.match(server, /path\.join\(ROOT, "\.env"\)/);
  assert.match(server, /SESSION_TTL_HOURS/);
  assert.match(server, /mva_procurement_uat/);
  assert.match(server, /om-leader-mai/);
  assert.match(server, /om-member-giang/);
  assert.match(server, /om-member-linh/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS users/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS sessions/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS om_assignments/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS uat_feedback/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS attachments/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS audit_events/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS item_master/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS material_identity/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS purchase_route_decisions/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS ftv_code_master/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS ftv_mapping_staging/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS customs_audit_records/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS sap_po_import_batches/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS sap_po_raw_lines/);
  assert.match(schema, /header_version VARCHAR\(80\) NOT NULL DEFAULT 'raw-data-a-bn-20260608'/);
  assert.match(schema, /factory_material_no VARCHAR\(120\)/);
  assert.match(schema, /sap_material_no VARCHAR\(120\)/);
  assert.match(schema, /buy_scope VARCHAR\(40\) NOT NULL DEFAULT 'mfg_buy'/);
  assert.match(schema, /scope_source VARCHAR\(80\) NOT NULL DEFAULT 'default_non_yellow'/);
  assert.match(schema, /source_fill_color VARCHAR\(40\)/);
  assert.match(schema, /normalized_item_name VARCHAR\(240\)/);
  assert.match(schema, /raw_payload_json JSON/);
  assert.match(schema, /INDEX idx_sap_po_raw_factory_material \(factory_material_no\)/);
  assert.match(schema, /INDEX idx_sap_po_raw_sap_material \(sap_material_no\)/);
  assert.match(schema, /INDEX idx_sap_po_raw_scope \(buy_scope, scope_source\)/);
  assert.match(sapPoRawMigration, /CREATE TABLE IF NOT EXISTS sap_po_import_batches/);
  assert.match(sapPoRawMigration, /CREATE TABLE IF NOT EXISTS sap_po_raw_lines/);
  assert.match(sapPoRawScopeMigration, /003_sap_po_raw_scope/);
  assert.match(sapPoRawScopeMigration, /information_schema\.columns/);
  assert.match(sapPoRawScopeMigration, /idx_sap_po_raw_scope/);
  assert.match(fs.readFileSync("scripts/extract_sap_po_raw_xlsx.py", "utf8"), /資訊類::電腦週邊::鍵盤/);
  assert.match(fs.readFileSync("scripts/extract_sap_po_raw_xlsx.py", "utf8"), /資訊類::條碼設備::條碼打印機/);
  assert.match(fs.readFileSync("scripts/extract_sap_po_raw_xlsx.py", "utf8"), /SUPPLEMENTAL_LV3_PREFIX_BY_PATH/);
  assert.match(schema, /route_type VARCHAR\(40\) NOT NULL/);
  assert.match(schema, /quote_owner VARCHAR\(40\) NOT NULL/);
  assert.match(schema, /demand_department VARCHAR\(120\) NOT NULL/);
  assert.match(schema, /UNIQUE KEY uq_ftv_item_department_active \(item_id, demand_department, active_scope_key\)/);
  assert.match(schema, /purchase_route VARCHAR\(40\) NOT NULL/);
  assert.match(fs.readFileSync("app-modules/ftv-code.js", "utf8"), /function ftvAuditKey/);
  assert.match(fs.readFileSync("app-modules/ftv-code.js", "utf8"), /function costAllocationKey/);
  assert.match(fs.readFileSync("app-modules/ftv-code.js", "utf8"), /ROUTE_LOCAL_BUY/);
  assert.match(fs.readFileSync("app-modules/ftv-code.js", "utf8"), /ROUTE_EXTERNAL_IMPORT/);
  assert.match(html, /app-modules\/sap-po-raw-contract\.js/);
  assert.match(sapPoRawContractModule, /MATERIAL_NO_TYPE_FACTORY = "factory_material_no"/);
  assert.match(sapPoRawContractModule, /BUY_SCOPE_OM = "om_scope"/);
  assert.match(sapPoRawContractModule, /SCOPE_SOURCE_EXCEL_YELLOW_FILL = "excel_yellow_fill"/);
  assert.match(sapPoRawContractModule, /\["A", "料號", "factory_material_no"\]/);
  assert.match(sapPoRawContractModule, /\["H", "料號", "sap_material_no"\]/);
  assert.match(sapPoRawContractModule, /\["Q", "正規化", "normalized_item_name"\]/);
  assert.match(sapPoRawContractModule, /\["BL", "Lv1", "lv1"\]/);
  assert.match(sapPoRawContractModule, /`\$\{column\.excelColumn\}:\$\{column\.header\}`/);
  assert.match(projectDecisions, /Raw Data.*column A.*Factory Material No/);
  assert.match(projectDecisions, /Column H.*SAP Material No/);
  assert.match(dataDictionary, /factory_material_no \| A `料號`/);
  assert.match(dataDictionary, /sap_material_no \| H `料號`/);
  assert.match(namingRulesZh, /Factory Material No.*A 欄 `料號`/);
  assert.match(namingRulesZh, /SAP Material No.*H 欄 `料號`/);
  assert.match(fs.readFileSync("test.sh", "utf8"), /app-modules\/ftv-code\.js/);
  assert.match(fs.readFileSync("test.sh", "utf8"), /app-modules\/sap-po-raw-contract\.js/);
  assert.match(fs.readFileSync("test.sh", "utf8"), /app-modules\/sap-po-raw-importer\.js/);
  assert.match(fs.readFileSync("test.sh", "utf8"), /scripts\/commit-sap-po-raw-import\.js/);
  assert.match(server, /\/api\/uat-feedback/);
  assert.match(server, /\/api\/attachments/);
  assert.match(server, /\/api\/admin\/sap-po-raw-import\/status/);
  assert.match(server, /\/api\/admin\/sap-po-raw-import\/preview/);
  assert.match(server, /\/api\/admin\/sap-po-raw-import\/commit/);
  assert.match(server, /sapPoRawImporter\.commitSapPoRawImport/);
  assert.match(server, /attachment\.uploaded/);
  assert.match(server, /UPLOAD_ROOT/);
  assert.match(server, /canTriageUatFeedback/);
  assert.match(server, /uat_feedback\.created/);
  assert.match(server, /uat_feedback\.status_updated/);
  assert.match(server, /uat_feedback\.owner_updated/);
  assert.match(app, /function assignOmRow/);
  assert.match(app, /function uploadAttachment/);
  assert.match(app, /screenshotAttachmentId/);
  assert.match(app, /function canOperateOmRow/);
  assert.match(html, /app-modules\/role-guards\.js/);
  assert.match(app, /ProcurementApp\?\.roleGuards\?\.canOperateOmRow/);
  assert.match(fs.readFileSync("app-modules/role-guards.js", "utf8"), /function canOperateOmRow/);
  assert.match(app, /function omAssignmentCell/);
  assert.match(app, /omAssigneeId/);
  assert.match(app, /data-om-assignee-id/);
  assert.doesNotMatch(app, /function canOperateOmRow\(row\) \{\s*if \(!isOmRole\(\)\) return true/);
  assert.match(styles, /\.om-assignment-control/);
  assert.match(styles, /\.om-pas-demand-table col\.om-pas-col-assignee/);
  assert.match(styles, /\.om-final-export-table col\.om-export-col-assignee/);
});

test("User-applied carryover stores VND price even when source row is USD canonical", () => {
  const helper = between(app, "function userCarryoverUnitPriceVnd", "function syncUserAppliedCarryoverLedger");
  assert.match(helper, /legacyPriceToUsd\(row, "updatedPrice"\)/);
  assert.match(helper, /legacyPriceToUsd\(row, "unitPrice"\)/);
  assert.match(helper, /legacyPriceToUsd\(row, "estimatedUnitPrice"\)/);
  assert.match(helper, /Math\.round\(amountVndFromUsd\(unitPriceUsd\)\)/);
  const sync = between(app, "function syncUserAppliedCarryoverLedger", "function renderDemandEditor");
  assert.match(sync, /unitPrice:\s*userCarryoverUnitPriceVnd\(row\)/);
  assert.match(sync, /unitPriceUsd:\s*amountUsdFromVnd\(userCarryoverUnitPriceVnd\(row\)\)/);
  const saving = between(app, "function managerCarryoverCostSaving", "function renderManagerCarryoverLedger");
  assert.match(saving, /row\.unitPriceUsd/);
  assert.match(saving, /amountUsdFromVnd\(clampQty\(row\.unitPrice\)\)/);
});

test("OM submission detail stays within OM ownership and export allows price-cleared rows", () => {
  const omDetail = between(app, "function openOmSubmissionDetail", "function compactList");
  assert.doesNotMatch(omDetail, /Budget Done/);
  assert.doesNotMatch(omDetail, /PR Done/);
  assert.doesNotMatch(omDetail, /PO Done/);
  assert.doesNotMatch(omDetail, /\["Arrived"/);
  assert.doesNotMatch(omDetail, /<th>PR #<\/th>/);
  assert.doesNotMatch(omDetail, /<th>PO #<\/th>/);
  assert.doesNotMatch(omDetail, /ETA \/ DTA/);
  assert.match(omDetail, /PAS Demand/);
  assert.match(omDetail, /Quote Result/);
  assert.match(omDetail, /User Confirm/);
  assert.match(omDetail, /Export Package/);
  const exportAuth = between(app, "function isOmExportAuthorized", "function isOmFinalExportPrepared");
  assert.match(exportAuth, /USER_CONFIRMATION_NOT_REQUIRED/);
  assert.match(exportAuth, /PRICE_AUTO_CLEARED/);
  assert.match(exportAuth, /PRICE_ESCALATION_APPROVED/);
});

test("Temporary budget and quote validity do not use active MutationObserver injection", () => {
  assert.doesNotMatch(app, /new MutationObserver/);
  assert.match(app, /window\.renderRequesterTempBudgetPanel = renderRequesterTempBudgetPanel/);
  assert.match(app, /Quote Valid Until/);
});

test("UI quality review documentation and skill are registered", () => {
  assert.ok(fs.existsSync("_doc/ui-quality-review.zh-TW.md"));
  assert.ok(fs.existsSync("_doc/ui-quality-review.en.md"));
  assert.ok(fs.existsSync("_doc/v0.6.md"));
  const testingZh = fs.readFileSync("_doc/testing-standard-op.zh-TW.md", "utf8");
  const testingEn = fs.readFileSync("_doc/testing-standard-op.en.md", "utf8");
  assert.match(testingZh, /procurement-ui-quality-review/);
  assert.match(testingEn, /procurement-ui-quality-review/);
});
