-- SAP / PO Raw Data mirror for Source DB regularize_0608_renumbered.xlsx.
-- Keeps Raw Data A-BN export/import shape while workflow tables stay canonical.

CREATE TABLE IF NOT EXISTS sap_po_import_batches (
  id VARCHAR(96) PRIMARY KEY,
  source_file_name VARCHAR(255) NOT NULL,
  source_sheet_name VARCHAR(120) NOT NULL DEFAULT 'Raw Data',
  header_version VARCHAR(80) NOT NULL DEFAULT 'raw-data-a-bn-20260608',
  source_checksum VARCHAR(128),
  import_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  imported_by_user_id VARCHAR(64),
  imported_at TIMESTAMP NULL,
  metadata_json JSON,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sap_po_batches_status (import_status),
  INDEX idx_sap_po_batches_source (source_file_name, source_sheet_name),
  CONSTRAINT fk_sap_po_batches_imported_by FOREIGN KEY (imported_by_user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS sap_po_raw_lines (
  id VARCHAR(96) PRIMARY KEY,
  import_batch_id VARCHAR(96),
  source_row_number INT,
  item_id VARCHAR(96),
  material_id VARCHAR(96),
  buy_scope VARCHAR(40) NOT NULL DEFAULT 'mfg_buy',
  scope_source VARCHAR(80) NOT NULL DEFAULT 'default_non_yellow',
  source_fill_color VARCHAR(40),
  factory_material_no VARCHAR(120),
  purchase_order_no VARCHAR(120),
  purchase_order_status VARCHAR(80),
  purchase_order_line_no VARCHAR(40),
  legal_entity_code VARCHAR(80),
  purchase_department_code VARCHAR(120),
  purchase_department_name VARCHAR(200),
  sap_material_no VARCHAR(120),
  sap_material_lv1 VARCHAR(120),
  sap_material_lv2 VARCHAR(120),
  ftv_code VARCHAR(120),
  part_name VARCHAR(500),
  part_name_detail VARCHAR(500),
  chinese_translation VARCHAR(500),
  standard_part_name VARCHAR(240),
  normalized_chinese_part_name VARCHAR(240),
  normalized_item_name VARCHAR(240),
  brand VARCHAR(160),
  normalized_spec VARCHAR(500),
  spec TEXT,
  uom VARCHAR(80),
  currency VARCHAR(20),
  purchase_quantity VARCHAR(80),
  request_unit_price_usd VARCHAR(80),
  purchase_unit_price_usd VARCHAR(80),
  purchase_amount_usd VARCHAR(80),
  request_unit_price_vnd VARCHAR(120),
  purchase_unit_price_vnd VARCHAR(120),
  purchase_amount_vnd VARCHAR(120),
  cumulative_accepted_qty VARCHAR(80),
  cumulative_issued_qty VARCHAR(80),
  issued_amount VARCHAR(120),
  vendor_code VARCHAR(120),
  vendor_short_name VARCHAR(200),
  unit_price_delta VARCHAR(80),
  price_delta_rate VARCHAR(80),
  purchase_date VARCHAR(80),
  scheduled_delivery_date VARCHAR(80),
  acceptance_date VARCHAR(80),
  is_overdue VARCHAR(20),
  buyer_account VARCHAR(120),
  buyer_name VARCHAR(200),
  pre_settlement_no VARCHAR(120),
  project_code VARCHAR(160),
  project_name VARCHAR(160),
  mva_or_reb VARCHAR(40),
  purchase_requisition_no VARCHAR(120),
  request_department_code VARCHAR(120),
  request_department_name VARCHAR(200),
  requester_name VARCHAR(200),
  request_date VARCHAR(80),
  requester_extension VARCHAR(80),
  request_type VARCHAR(160),
  po_release_at VARCHAR(80),
  quotation_no VARCHAR(120),
  payment_terms VARCHAR(80),
  delivery_term VARCHAR(80),
  tax_rate VARCHAR(80),
  expense_account_code VARCHAR(120),
  purchase_requisition_release_time VARCHAR(80),
  expense_type VARCHAR(160),
  settlement_no VARCHAR(120),
  review_status VARCHAR(160),
  lv1 VARCHAR(120),
  lv2 VARCHAR(120),
  lv3 VARCHAR(120),
  raw_payload_json JSON,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sap_po_raw_batch (import_batch_id),
  INDEX idx_sap_po_raw_factory_material (factory_material_no),
  INDEX idx_sap_po_raw_sap_material (sap_material_no),
  INDEX idx_sap_po_raw_po (purchase_order_no, purchase_order_line_no),
  INDEX idx_sap_po_raw_item (item_id),
  INDEX idx_sap_po_raw_material (material_id),
  INDEX idx_sap_po_raw_scope (buy_scope, scope_source),
  INDEX idx_sap_po_raw_normalized_item (normalized_item_name),
  INDEX idx_sap_po_raw_category (lv1, lv2, lv3),
  CONSTRAINT fk_sap_po_raw_batch FOREIGN KEY (import_batch_id) REFERENCES sap_po_import_batches(id),
  CONSTRAINT fk_sap_po_raw_item FOREIGN KEY (item_id) REFERENCES item_master(id),
  CONSTRAINT fk_sap_po_raw_material FOREIGN KEY (material_id) REFERENCES material_identity(id)
);

INSERT INTO schema_migrations (version, description)
VALUES ('002_sap_po_raw_mirror', 'Add SAP PO raw mirror tables for Raw Data A-BN')
ON DUPLICATE KEY UPDATE description = VALUES(description);
